/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- */
/* libu8ident - Check unicode security guidelines for identifiers.
   Copyright 2021, 2022 Reini Urban
   SPDX-License-Identifier: Apache-2.0

   generated by mkc23, do not modify.
   UNICODE version 14.0
   Filtered XID_Start/Continue with allowed scripts, !Limited_Use,!Obsolete,!Uncommon_Use and NFC
*/
// Filtering allowed scripts, XID_Start, Skipped Ids and NFC
const struct sc safec23_start_list[] = {
    {'$', '$', SC_Latin},
    {'A', 'Z', SC_Latin},
    {'_', '_', SC_Latin},
    {'a', 'z', SC_Latin},
    {0x7A, 0x7A, 2}, // Latin z
    {0xAA, 0xAA, 2}, // Latin ª
    {0xB5, 0xB5, 0}, // Common µ
    {0xBA, 0xBA, 2}, // Latin º
    {0xC0, 0xD6, 2}, // Latin À..Ö
    {0xD8, 0xF6, 2}, // Latin Ø..ö
    {0xF8, 0x2B8, 2}, // Latin ø..ʸ
    {0x2BA, 0x2C1, 0}, // Common ʺ..ˁ
    {0x2C6, 0x2D1, 0}, // Common ˆ..ˑ
    {0x2E0, 0x2E4, 2}, // Latin ˠ..ˤ
    {0x2EC, 0x2EC, 0}, // Common ˬ
    {0x2EE, 0x2EE, 0}, // Common ˮ
    {0x370, 0x373, 11}, // Greek Ͱ..ͳ
    {0x376, 0x377, 11}, // Greek Ͷ..ͷ
    {0x37B, 0x37D, 11}, // Greek ͻ..ͽ
    {0x37F, 0x37F, 11}, // Greek Ϳ
    {0x386, 0x386, 11}, // Greek Ά
    {0x388, 0x38A, 11}, // Greek Έ..Ί
    {0x38C, 0x38C, 11}, // Greek Ό
    {0x38E, 0x3A1, 11}, // Greek Ύ..Ρ
    {0x3A3, 0x3E1, 11}, // Greek Σ..ϡ
    {0x3F0, 0x3F5, 11}, // Greek ϰ..ϵ
    {0x3F7, 0x3FF, 11}, // Greek Ϸ..Ͽ
    {0x401, 0x481, 7}, // Cyrillic Ё..ҁ
    {0x48A, 0x52F, 7}, // Cyrillic Ҋ..ԯ
    {0x531, 0x556, 4}, // Armenian Ա..Ֆ
    {0x559, 0x559, 4}, // Armenian ՙ
    {0x560, 0x588, 4}, // Armenian ՠ..ֈ
    {0x5D0, 0x5EA, 16}, // Hebrew א..ת
    {0x5EF, 0x5F2, 16}, // Hebrew ׯ..ײ
    {0x620, 0x63F, 3}, // Arabic ؠ..ؿ
    {0x641, 0x64A, 3}, // Arabic ف..ي
    {0x66E, 0x66F, 3}, // Arabic ٮ..ٯ
    {0x671, 0x6D3, 3}, // Arabic ٱ..ۓ
    {0x6D5, 0x6D5, 3}, // Arabic ە
    {0x6E5, 0x6E6, 3}, // Arabic ۥ..ۦ
    {0x6EE, 0x6EF, 3}, // Arabic ۮ..ۯ
    {0x6FA, 0x6FC, 3}, // Arabic ۺ..ۼ
    {0x6FF, 0x6FF, 3}, // Arabic ۿ
    {0x750, 0x77F, 3}, // Arabic ݐ..ݿ
    {0x781, 0x7A5, 28}, // Thaana ށ..ޥ
    {0x7B1, 0x7B1, 28}, // Thaana ޱ
    {0x870, 0x887, 3}, // Arabic ࡰ..ࢇ
    {0x889, 0x88E, 3}, // Arabic ࢉ..ࢎ
    {0x8A0, 0x8C9, 3}, // Arabic ࢠ..ࣉ
    {0x904, 0x939, 8}, // Devanagari ऄ..ह
    {0x93D, 0x93D, 8}, // Devanagari ऽ
    {0x950, 0x950, 8}, // Devanagari ॐ
    {0x960, 0x961, 8}, // Devanagari ॠ..ॡ
    {0x971, 0x97F, 8}, // Devanagari ॱ..ॿ
    {0x985, 0x98C, 5}, // Bengali অ..ঌ
    {0x98F, 0x990, 5}, // Bengali এ..ঐ
    {0x993, 0x9A8, 5}, // Bengali ও..ন
    {0x9AA, 0x9B0, 5}, // Bengali প..র
    {0x9B2, 0x9B2, 5}, // Bengali ল
    {0x9B6, 0x9B9, 5}, // Bengali শ..হ
    {0x9BD, 0x9BD, 5}, // Bengali ঽ
    {0x9CE, 0x9CE, 5}, // Bengali ৎ
    {0x9E0, 0x9E1, 5}, // Bengali ৠ..ৡ
    {0x9F0, 0x9F1, 5}, // Bengali ৰ..ৱ
    {0x9FC, 0x9FC, 5}, // Bengali ৼ
    {0xA05, 0xA0A, 13}, // Gurmukhi ਅ..ਊ
    {0xA0F, 0xA10, 13}, // Gurmukhi ਏ..ਐ
    {0xA13, 0xA28, 13}, // Gurmukhi ਓ..ਨ
    {0xA2A, 0xA30, 13}, // Gurmukhi ਪ..ਰ
    {0xA32, 0xA32, 13}, // Gurmukhi ਲ
    {0xA35, 0xA35, 13}, // Gurmukhi ਵ
    {0xA38, 0xA39, 13}, // Gurmukhi ਸ..ਹ
    {0xA5C, 0xA5C, 13}, // Gurmukhi ੜ
    {0xA72, 0xA74, 13}, // Gurmukhi ੲ..ੴ
    {0xA85, 0xA8D, 12}, // Gujarati અ..ઍ
    {0xA8F, 0xA91, 12}, // Gujarati એ..ઑ
    {0xA93, 0xAA8, 12}, // Gujarati ઓ..ન
    {0xAAA, 0xAB0, 12}, // Gujarati પ..ર
    {0xAB2, 0xAB3, 12}, // Gujarati લ..ળ
    {0xAB5, 0xAB9, 12}, // Gujarati વ..હ
    {0xABD, 0xABD, 12}, // Gujarati ઽ
    {0xAD0, 0xAD0, 12}, // Gujarati ૐ
    {0xAE0, 0xAE1, 12}, // Gujarati ૠ..ૡ
    {0xAF9, 0xAF9, 12}, // Gujarati ૹ
    {0xB05, 0xB0C, 24}, // Oriya ଅ..ଌ
    {0xB0F, 0xB10, 24}, // Oriya ଏ..ଐ
    {0xB13, 0xB28, 24}, // Oriya ଓ..ନ
    {0xB2A, 0xB30, 24}, // Oriya ପ..ର
    {0xB32, 0xB33, 24}, // Oriya ଲ..ଳ
    {0xB35, 0xB39, 24}, // Oriya ଵ..ହ
    {0xB3D, 0xB3D, 24}, // Oriya ଽ
    {0xB5F, 0xB61, 24}, // Oriya ୟ..ୡ
    {0xB71, 0xB71, 24}, // Oriya ୱ
    {0xB83, 0xB83, 26}, // Tamil ஃ
    {0xB85, 0xB8A, 26}, // Tamil அ..ஊ
    {0xB8E, 0xB90, 26}, // Tamil எ..ஐ
    {0xB92, 0xB95, 26}, // Tamil ஒ..க
    {0xB99, 0xB9A, 26}, // Tamil ங..ச
    {0xB9C, 0xB9C, 26}, // Tamil ஜ
    {0xB9E, 0xB9F, 26}, // Tamil ஞ..ட
    {0xBA3, 0xBA4, 26}, // Tamil ண..த
    {0xBA8, 0xBAA, 26}, // Tamil ந..ப
    {0xBAE, 0xBB9, 26}, // Tamil ம..ஹ
    {0xBD0, 0xBD0, 26}, // Tamil ௐ
    {0xC05, 0xC0C, 27}, // Telugu అ..ఌ
    {0xC0E, 0xC10, 27}, // Telugu ఎ..ఐ
    {0xC12, 0xC28, 27}, // Telugu ఒ..న
    {0xC2A, 0xC39, 27}, // Telugu ప..హ
    {0xC3D, 0xC3D, 27}, // Telugu ఽ
    {0xC58, 0xC5A, 27}, // Telugu ౘ..ౚ
    {0xC5D, 0xC5D, 27}, // Telugu ౝ
    {0xC60, 0xC61, 27}, // Telugu ౠ..ౡ
    {0xC80, 0xC80, 19}, // Kannada ಀ
    {0xC85, 0xC8C, 19}, // Kannada ಅ..ಌ
    {0xC8E, 0xC90, 19}, // Kannada ಎ..ಐ
    {0xC92, 0xCA8, 19}, // Kannada ಒ..ನ
    {0xCAA, 0xCB3, 19}, // Kannada ಪ..ಳ
    {0xCB5, 0xCB9, 19}, // Kannada ವ..ಹ
    {0xCBD, 0xCBD, 19}, // Kannada ಽ
    {0xCDD, 0xCDE, 19}, // Kannada ೝ..ೞ
    {0xCE0, 0xCE1, 19}, // Kannada ೠ..ೡ
    {0xCF1, 0xCF2, 19}, // Kannada ೱ..ೲ
    {0xD04, 0xD0C, 22}, // Malayalam ഄ..ഌ
    {0xD0E, 0xD10, 22}, // Malayalam എ..ഐ
    {0xD12, 0xD3A, 22}, // Malayalam ഒ..ഺ
    {0xD3D, 0xD3D, 22}, // Malayalam ഽ
    {0xD4E, 0xD4E, 22}, // Malayalam ൎ
    {0xD54, 0xD56, 22}, // Malayalam ൔ..ൖ
    {0xD5F, 0xD61, 22}, // Malayalam ൟ..ൡ
    {0xD7A, 0xD7F, 22}, // Malayalam ൺ..ൿ
    {0xD85, 0xD96, 25}, // Sinhala අ..ඖ
    {0xD9A, 0xDB1, 25}, // Sinhala ක..න
    {0xDB3, 0xDBB, 25}, // Sinhala ඳ..ර
    {0xDBD, 0xDBD, 25}, // Sinhala ල
    {0xDC0, 0xDC6, 25}, // Sinhala ව..ෆ
    {0xE01, 0xE30, 29}, // Thai ก..ะ
    {0xE32, 0xE32, 29}, // Thai า
    {0xE40, 0xE46, 29}, // Thai เ..ๆ
    {0xE81, 0xE82, 21}, // Lao ກ..ຂ
    {0xE84, 0xE84, 21}, // Lao ຄ
    {0xE86, 0xE8A, 21}, // Lao ຆ..ຊ
    {0xE8C, 0xEA3, 21}, // Lao ຌ..ຣ
    {0xEA5, 0xEA5, 21}, // Lao ລ
    {0xEA7, 0xEB0, 21}, // Lao ວ..ະ
    {0xEB2, 0xEB2, 21}, // Lao າ
    {0xEBD, 0xEBD, 21}, // Lao ຽ
    {0xEC0, 0xEC4, 21}, // Lao ເ..ໄ
    {0xEC6, 0xEC6, 21}, // Lao ໆ
    {0xEDC, 0xEDF, 21}, // Lao ໜ..ໟ
    {0xF00, 0xF00, 30}, // Tibetan ༀ
    {0xF40, 0xF42, 30}, // Tibetan ཀ..ག
    {0xF44, 0xF47, 30}, // Tibetan ང..ཇ
    {0xF49, 0xF4C, 30}, // Tibetan ཉ..ཌ
    {0xF4E, 0xF51, 30}, // Tibetan ཎ..ད
    {0xF53, 0xF56, 30}, // Tibetan ན..བ
    {0xF58, 0xF5B, 30}, // Tibetan མ..ཛ
    {0xF5D, 0xF68, 30}, // Tibetan ཝ..ཨ
    {0xF6A, 0xF6C, 30}, // Tibetan ཪ..ཬ
    {0xF88, 0xF8C, 30}, // Tibetan ྈ..ྌ
    {0x1000, 0x102A, 23}, // Myanmar က..ဪ
    {0x103F, 0x103F, 23}, // Myanmar ဿ
    {0x1050, 0x1055, 23}, // Myanmar ၐ..ၕ
    {0x105A, 0x105D, 23}, // Myanmar ၚ..ၝ
    {0x1061, 0x1061, 23}, // Myanmar ၡ
    {0x1065, 0x1066, 23}, // Myanmar ၥ..ၦ
    {0x106E, 0x1070, 23}, // Myanmar ၮ..ၰ
    {0x1075, 0x1081, 23}, // Myanmar ၵ..ႁ
    {0x108E, 0x108E, 23}, // Myanmar ႎ
    {0x10A0, 0x10C5, 10}, // Georgian Ⴀ..Ⴥ
    {0x10C7, 0x10C7, 10}, // Georgian Ⴧ
    {0x10CD, 0x10CD, 10}, // Georgian Ⴭ
    {0x10D0, 0x10FA, 10}, // Georgian ა..ჺ
    {0x10FC, 0x10FF, 10}, // Georgian ჼ..ჿ
    {0x1101, 0x11FF, 14}, // Hangul ᄁ..ᇿ
    {0x1201, 0x1248, 9}, // Ethiopic ሁ..ቈ
    {0x124A, 0x124D, 9}, // Ethiopic ቊ..ቍ
    {0x1250, 0x1256, 9}, // Ethiopic ቐ..ቖ
    {0x1258, 0x1258, 9}, // Ethiopic ቘ
    {0x125A, 0x125D, 9}, // Ethiopic ቚ..ቝ
    {0x1260, 0x1288, 9}, // Ethiopic በ..ኈ
    {0x128A, 0x128D, 9}, // Ethiopic ኊ..ኍ
    {0x1290, 0x12B0, 9}, // Ethiopic ነ..ኰ
    {0x12B2, 0x12B5, 9}, // Ethiopic ኲ..ኵ
    {0x12B8, 0x12BE, 9}, // Ethiopic ኸ..ኾ
    {0x12C0, 0x12C0, 9}, // Ethiopic ዀ
    {0x12C2, 0x12C5, 9}, // Ethiopic ዂ..ዅ
    {0x12C8, 0x12D6, 9}, // Ethiopic ወ..ዖ
    {0x12D8, 0x1310, 9}, // Ethiopic ዘ..ጐ
    {0x1312, 0x1315, 9}, // Ethiopic ጒ..ጕ
    {0x1318, 0x135A, 9}, // Ethiopic ጘ..ፚ
    {0x1380, 0x138F, 9}, // Ethiopic ᎀ..ᎏ
    {0x1780, 0x17B3, 20}, // Khmer ក..ឳ
    {0x17D7, 0x17D7, 20}, // Khmer ៗ
    {0x17DC, 0x17DC, 20}, // Khmer ៜ
    {0x1C80, 0x1C88, 7}, // Cyrillic ᲀ..ᲈ
    {0x1C90, 0x1CBA, 10}, // Georgian Ა..Ჺ
    {0x1CBD, 0x1CBF, 10}, // Georgian Ჽ..Ჿ
    {0x1CEB, 0x1CEC, 8}, // Devanagari ᳫ..ᳬ
    {0x1CEE, 0x1CF1, 8}, // Devanagari ᳮ..ᳱ
    {0x1CF5, 0x1CF6, 0}, // Common ᳵ..ᳶ
    {0x1D00, 0x1D25, 2}, // Latin ᴀ..ᴥ
    {0x1D27, 0x1D2A, 11}, // Greek ᴧ..ᴪ
    {0x1D2C, 0x1D5C, 2}, // Latin ᴬ..ᵜ
    {0x1D5E, 0x1D61, 11}, // Greek ᵞ..ᵡ
    {0x1D63, 0x1D65, 2}, // Latin ᵣ..ᵥ
    {0x1D67, 0x1D6A, 11}, // Greek ᵧ..ᵪ
    {0x1D6C, 0x1D77, 2}, // Latin ᵬ..ᵷ
    {0x1D79, 0x1DBE, 2}, // Latin ᵹ..ᶾ
    {0x1E00, 0x1EFF, 2}, // Latin Ḁ..ỿ
    {0x1F01, 0x1F15, 11}, // Greek ἁ..ἕ
    {0x1F18, 0x1F1D, 11}, // Greek Ἐ..Ἕ
    {0x1F20, 0x1F45, 11}, // Greek ἠ..ὅ
    {0x1F48, 0x1F4D, 11}, // Greek Ὀ..Ὅ
    {0x1F50, 0x1F57, 11}, // Greek ὐ..ὗ
    {0x1F59, 0x1F59, 11}, // Greek Ὑ
    {0x1F5B, 0x1F5B, 11}, // Greek Ὓ
    {0x1F5D, 0x1F5D, 11}, // Greek Ὕ
    {0x1F5F, 0x1F70, 11}, // Greek Ὗ..ὰ
    {0x1F72, 0x1F72, 11}, // Greek ὲ
    {0x1F74, 0x1F74, 11}, // Greek ὴ
    {0x1F76, 0x1F76, 11}, // Greek ὶ
    {0x1F78, 0x1F78, 11}, // Greek ὸ
    {0x1F7A, 0x1F7A, 11}, // Greek ὺ
    {0x1F7C, 0x1F7C, 11}, // Greek ὼ
    {0x1F80, 0x1FB4, 11}, // Greek ᾀ..ᾴ
    {0x1FB6, 0x1FBA, 11}, // Greek ᾶ..Ὰ
    {0x1FBC, 0x1FBC, 11}, // Greek ᾼ
    {0x1FC2, 0x1FC4, 11}, // Greek ῂ..ῄ
    {0x1FC6, 0x1FC8, 11}, // Greek ῆ..Ὲ
    {0x1FCA, 0x1FCA, 11}, // Greek Ὴ
    {0x1FCC, 0x1FCC, 11}, // Greek ῌ
    {0x1FD0, 0x1FD2, 11}, // Greek ῐ..ῒ
    {0x1FD6, 0x1FDA, 11}, // Greek ῖ..Ὶ
    {0x1FE0, 0x1FE2, 11}, // Greek ῠ..ῢ
    {0x1FE4, 0x1FEA, 11}, // Greek ῤ..Ὺ
    {0x1FEC, 0x1FEC, 11}, // Greek Ῥ
    {0x1FF2, 0x1FF4, 11}, // Greek ῲ..ῴ
    {0x1FF6, 0x1FF8, 11}, // Greek ῶ..Ὸ
    {0x1FFA, 0x1FFA, 11}, // Greek Ὼ
    {0x1FFC, 0x1FFC, 11}, // Greek ῼ
    {0x2071, 0x2071, 2}, // Latin ⁱ
    {0x207F, 0x207F, 2}, // Latin ⁿ
    {0x2090, 0x209C, 2}, // Latin ₐ..ₜ
    {0x2102, 0x2102, 0}, // Common ℂ
    {0x2107, 0x2107, 0}, // Common ℇ
    {0x210A, 0x2113, 0}, // Common ℊ..ℓ
    {0x2115, 0x2115, 0}, // Common ℕ
    {0x2118, 0x211D, 0}, // Common ℘..ℝ
    {0x2124, 0x2124, 0}, // Common ℤ
    {0x2128, 0x2128, 0}, // Common ℨ
    {0x212C, 0x2131, 0}, // Common ℬ..ℱ
    {0x2133, 0x2139, 0}, // Common ℳ..ℹ
    {0x213C, 0x213F, 0}, // Common ℼ..ℿ
    {0x2145, 0x2149, 0}, // Common ⅅ..ⅉ
    {0x214E, 0x214E, 2}, // Latin ⅎ
    {0x2160, 0x2188, 2}, // Latin Ⅰ..ↈ
    {0x2C60, 0x2C7F, 2}, // Latin Ⱡ..Ɀ
    {0x2D00, 0x2D25, 10}, // Georgian ⴀ..ⴥ
    {0x2D27, 0x2D27, 10}, // Georgian ⴧ
    {0x2D2D, 0x2D2D, 10}, // Georgian ⴭ
    {0x2D80, 0x2D96, 9}, // Ethiopic ⶀ..ⶖ
    {0x2DA0, 0x2DA6, 9}, // Ethiopic ⶠ..ⶦ
    {0x2DA8, 0x2DAE, 9}, // Ethiopic ⶨ..ⶮ
    {0x2DB0, 0x2DB6, 9}, // Ethiopic ⶰ..ⶶ
    {0x2DB8, 0x2DBE, 9}, // Ethiopic ⶸ..ⶾ
    {0x2DC0, 0x2DC6, 9}, // Ethiopic ⷀ..ⷆ
    {0x2DC8, 0x2DCE, 9}, // Ethiopic ⷈ..ⷎ
    {0x2DD0, 0x2DD6, 9}, // Ethiopic ⷐ..ⷖ
    {0x2DD8, 0x2DDE, 9}, // Ethiopic ⷘ..ⷞ
    {0x3005, 0x3007, 15}, // Han 々..〇
    {0x3021, 0x3029, 15}, // Han 〡..〩
    {0x3031, 0x3035, 0}, // Common 〱..〵
    {0x3038, 0x303B, 15}, // Han 〸..〻
    {0x3041, 0x3096, 17}, // Hiragana ぁ..ゖ
    {0x309D, 0x309F, 17}, // Hiragana ゝ..ゟ
    {0x30A1, 0x30FA, 18}, // Katakana ァ..ヺ
    {0x30FC, 0x30FC, 0}, // Common ー
    {0x30FE, 0x30FF, 18}, // Katakana ヾ..ヿ
    {0x3105, 0x312F, 6}, // Bopomofo ㄅ..ㄯ
    {0x3131, 0x318E, 14}, // Hangul ㄱ..ㆎ
    {0x31A0, 0x31BF, 6}, // Bopomofo ㆠ..ㆿ
    {0x31F0, 0x31FF, 18}, // Katakana ㇰ..ㇿ
    {0x4E00, 0x9FFF, 15}, // Han 一..鿿
    {0xA640, 0xA66E, 7}, // Cyrillic Ꙁ..ꙮ
    {0xA67F, 0xA69D, 7}, // Cyrillic ꙿ..ꚝ
    {0xA717, 0xA71F, 0}, // Common ꜗ..ꜟ
    {0xA722, 0xA787, 2}, // Latin Ꜣ..ꞇ
    {0xA78B, 0xA7CA, 2}, // Latin Ꞌ..ꟊ
    {0xA7D0, 0xA7D1, 2}, // Latin Ꟑ..ꟑ
    {0xA7D3, 0xA7D3, 2}, // Latin ꟓ
    {0xA7D5, 0xA7D9, 2}, // Latin ꟕ..ꟙ
    {0xA7F2, 0xA7FF, 2}, // Latin ꟲ..ꟿ
    {0xA8F2, 0xA8F7, 8}, // Devanagari ꣲ..ꣷ
    {0xA8FB, 0xA8FB, 8}, // Devanagari ꣻ
    {0xA8FD, 0xA8FE, 8}, // Devanagari ꣽ..ꣾ
    {0xA960, 0xA97C, 14}, // Hangul ꥠ..ꥼ
    {0xA9CF, 0xA9CF, 0}, // Common ꧏ
    {0xA9E0, 0xA9E4, 23}, // Myanmar ꧠ..ꧤ
    {0xA9E6, 0xA9EF, 23}, // Myanmar ꧦ..ꧯ
    {0xA9FA, 0xA9FE, 23}, // Myanmar ꧺ..ꧾ
    {0xAA60, 0xAA76, 23}, // Myanmar ꩠ..ꩶ
    {0xAA7A, 0xAA7A, 23}, // Myanmar ꩺ
    {0xAA7E, 0xAA7F, 23}, // Myanmar ꩾ..ꩿ
    {0xAB01, 0xAB06, 9}, // Ethiopic ꬁ..ꬆ
    {0xAB09, 0xAB0E, 9}, // Ethiopic ꬉ..ꬎ
    {0xAB11, 0xAB16, 9}, // Ethiopic ꬑ..ꬖ
    {0xAB20, 0xAB26, 9}, // Ethiopic ꬠ..ꬦ
    {0xAB28, 0xAB2E, 9}, // Ethiopic ꬨ..ꬮ
    {0xAB30, 0xAB5A, 2}, // Latin ꬰ..ꭚ
    {0xAB5C, 0xAB64, 2}, // Latin ꭜ..ꭤ
    {0xAB66, 0xAB69, 2}, // Latin ꭦ..ꭩ
    {0xD7B0, 0xD7C6, 14}, // Hangul ힰ..ퟆ
    {0xD7CB, 0xD7FB, 14}, // Hangul ퟋ..ퟻ
    {0xFA0E, 0xFA0F, 15}, // Han 﨎..﨏
    {0xFA11, 0xFA11, 15}, // Han 﨑
    {0xFA13, 0xFA14, 15}, // Han 﨓..﨔
    {0xFA1F, 0xFA1F, 15}, // Han 﨟
    {0xFA21, 0xFA21, 15}, // Han 﨡
    {0xFA23, 0xFA24, 15}, // Han 﨣..﨤
    {0xFA27, 0xFA29, 15}, // Han 﨧..﨩
    {0xFB00, 0xFB06, 2}, // Latin ﬀ..ﬆ
    {0xFB13, 0xFB17, 4}, // Armenian ﬓ..ﬗ
    {0xFB20, 0xFB28, 16}, // Hebrew ﬠ..ﬨ
    {0xFB4F, 0xFB4F, 16}, // Hebrew ﭏ
    {0xFB51, 0xFBB1, 3}, // Arabic ﭑ..ﮱ
    {0xFBD3, 0xFC5D, 3}, // Arabic ﯓ..ﱝ
    {0xFC64, 0xFD3D, 3}, // Arabic ﱤ..ﴽ
    {0xFD50, 0xFD8F, 3}, // Arabic ﵐ..ﶏ
    {0xFD92, 0xFDC7, 3}, // Arabic ﶒ..ﷇ
    {0xFDF0, 0xFDF9, 3}, // Arabic ﷰ..ﷹ
    {0xFE71, 0xFE71, 3}, // Arabic ﹱ
    {0xFE73, 0xFE73, 3}, // Arabic ﹳ
    {0xFE77, 0xFE77, 3}, // Arabic ﹷ
    {0xFE79, 0xFE79, 3}, // Arabic ﹹ
    {0xFE7B, 0xFE7B, 3}, // Arabic ﹻ
    {0xFE7D, 0xFE7D, 3}, // Arabic ﹽ
    {0xFE7F, 0xFEFC, 3}, // Arabic ﹿ..ﻼ
    {0xFF21, 0xFF3A, 2}, // Latin Ａ..Ｚ
    {0xFF41, 0xFF5A, 2}, // Latin ａ..ｚ
    {0xFF66, 0xFF6F, 18}, // Katakana ｦ..ｯ
    {0xFF71, 0xFF9D, 18}, // Katakana ｱ..ﾝ
    {0xFFA0, 0xFFBE, 14}, // Hangul ﾠ..ﾾ
    {0xFFC2, 0xFFC7, 14}, // Hangul ￂ..ￇ
    {0xFFCA, 0xFFCF, 14}, // Hangul ￊ..ￏ
    {0xFFD2, 0xFFD7, 14}, // Hangul ￒ..ￗ
    {0xFFDA, 0xFFDC, 14}, // Hangul ￚ..ￜ
    {0x10140, 0x10174, 11}, // Greek 𐅀..𐅴
    {0x10780, 0x10785, 2}, // Latin 𐞀..𐞅
    {0x10787, 0x107B0, 2}, // Latin 𐞇..𐞰
    {0x107B2, 0x107BA, 2}, // Latin 𐞲..𐞺
    {0x16FE3, 0x16FE3, 15}, // Han 𖿣
    {0x1AFF0, 0x1AFF3, 18}, // Katakana 𚿰..𚿳
    {0x1AFF5, 0x1AFFB, 18}, // Katakana 𚿵..𚿻
    {0x1AFFD, 0x1AFFE, 18}, // Katakana 𚿽..𚿾
    {0x1B000, 0x1B000, 18}, // Katakana 𛀀
    {0x1B002, 0x1B11F, 17}, // Hiragana 𛀂..𛄟
    {0x1B121, 0x1B122, 18}, // Katakana 𛄡..𛄢
    {0x1B150, 0x1B152, 17}, // Hiragana 𛅐..𛅒
    {0x1B164, 0x1B167, 18}, // Katakana 𛅤..𛅧
    {0x1D400, 0x1D454, 0}, // Common 𝐀..𝑔
    {0x1D456, 0x1D49C, 0}, // Common 𝑖..𝒜
    {0x1D49E, 0x1D49F, 0}, // Common 𝒞..𝒟
    {0x1D4A2, 0x1D4A2, 0}, // Common 𝒢
    {0x1D4A5, 0x1D4A6, 0}, // Common 𝒥..𝒦
    {0x1D4A9, 0x1D4AC, 0}, // Common 𝒩..𝒬
    {0x1D4AE, 0x1D4B9, 0}, // Common 𝒮..𝒹
    {0x1D4BB, 0x1D4BB, 0}, // Common 𝒻
    {0x1D4BD, 0x1D4C3, 0}, // Common 𝒽..𝓃
    {0x1D4C5, 0x1D505, 0}, // Common 𝓅..𝔅
    {0x1D507, 0x1D50A, 0}, // Common 𝔇..𝔊
    {0x1D50D, 0x1D514, 0}, // Common 𝔍..𝔔
    {0x1D516, 0x1D51C, 0}, // Common 𝔖..𝔜
    {0x1D51E, 0x1D539, 0}, // Common 𝔞..𝔹
    {0x1D53B, 0x1D53E, 0}, // Common 𝔻..𝔾
    {0x1D540, 0x1D544, 0}, // Common 𝕀..𝕄
    {0x1D546, 0x1D546, 0}, // Common 𝕆
    {0x1D54A, 0x1D550, 0}, // Common 𝕊..𝕐
    {0x1D552, 0x1D6A5, 0}, // Common 𝕒..𝚥
    {0x1D6A8, 0x1D6C0, 0}, // Common 𝚨..𝛀
    {0x1D6C2, 0x1D6DA, 0}, // Common 𝛂..𝛚
    {0x1D6DC, 0x1D6FA, 0}, // Common 𝛜..𝛺
    {0x1D6FC, 0x1D714, 0}, // Common 𝛼..𝜔
    {0x1D716, 0x1D734, 0}, // Common 𝜖..𝜴
    {0x1D736, 0x1D74E, 0}, // Common 𝜶..𝝎
    {0x1D750, 0x1D76E, 0}, // Common 𝝐..𝝮
    {0x1D770, 0x1D788, 0}, // Common 𝝰..𝞈
    {0x1D78A, 0x1D7A8, 0}, // Common 𝞊..𝞨
    {0x1D7AA, 0x1D7C2, 0}, // Common 𝞪..𝟂
    {0x1D7C4, 0x1D7CB, 0}, // Common 𝟄..𝟋
    {0x1DF00, 0x1DF1E, 2}, // Latin 𝼀..𝼞
    {0x1E7E0, 0x1E7E6, 9}, // Ethiopic 𞟠..𞟦
    {0x1E7E8, 0x1E7EB, 9}, // Ethiopic 𞟨..𞟫
    {0x1E7ED, 0x1E7EE, 9}, // Ethiopic 𞟭..𞟮
    {0x1E7F0, 0x1E7FE, 9}, // Ethiopic 𞟰..𞟾
    {0x1EE00, 0x1EE03, 3}, // Arabic 𞸀..𞸃
    {0x1EE05, 0x1EE1F, 3}, // Arabic 𞸅..𞸟
    {0x1EE21, 0x1EE22, 3}, // Arabic 𞸡..𞸢
    {0x1EE24, 0x1EE24, 3}, // Arabic 𞸤
    {0x1EE27, 0x1EE27, 3}, // Arabic 𞸧
    {0x1EE29, 0x1EE32, 3}, // Arabic 𞸩..𞸲
    {0x1EE34, 0x1EE37, 3}, // Arabic 𞸴..𞸷
    {0x1EE39, 0x1EE39, 3}, // Arabic 𞸹
    {0x1EE3B, 0x1EE3B, 3}, // Arabic 𞸻
    {0x1EE42, 0x1EE42, 3}, // Arabic 𞹂
    {0x1EE47, 0x1EE47, 3}, // Arabic 𞹇
    {0x1EE49, 0x1EE49, 3}, // Arabic 𞹉
    {0x1EE4B, 0x1EE4B, 3}, // Arabic 𞹋
    {0x1EE4D, 0x1EE4F, 3}, // Arabic 𞹍..𞹏
    {0x1EE51, 0x1EE52, 3}, // Arabic 𞹑..𞹒
    {0x1EE54, 0x1EE54, 3}, // Arabic 𞹔
    {0x1EE57, 0x1EE57, 3}, // Arabic 𞹗
    {0x1EE59, 0x1EE59, 3}, // Arabic 𞹙
    {0x1EE5B, 0x1EE5B, 3}, // Arabic 𞹛
    {0x1EE5D, 0x1EE5D, 3}, // Arabic 𞹝
    {0x1EE5F, 0x1EE5F, 3}, // Arabic 𞹟
    {0x1EE61, 0x1EE62, 3}, // Arabic 𞹡..𞹢
    {0x1EE64, 0x1EE64, 3}, // Arabic 𞹤
    {0x1EE67, 0x1EE6A, 3}, // Arabic 𞹧..𞹪
    {0x1EE6C, 0x1EE72, 3}, // Arabic 𞹬..𞹲
    {0x1EE74, 0x1EE77, 3}, // Arabic 𞹴..𞹷
    {0x1EE79, 0x1EE7C, 3}, // Arabic 𞹹..𞹼
    {0x1EE7E, 0x1EE7E, 3}, // Arabic 𞹾
    {0x1EE80, 0x1EE89, 3}, // Arabic 𞺀..𞺉
    {0x1EE8B, 0x1EE9B, 3}, // Arabic 𞺋..𞺛
    {0x1EEA1, 0x1EEA3, 3}, // Arabic 𞺡..𞺣
    {0x1EEA5, 0x1EEA9, 3}, // Arabic 𞺥..𞺩
    {0x1EEAB, 0x1EEBB, 3}, // Arabic 𞺫..𞺻
    {0x20000, 0x2A6DF, 15}, // Han 𠀀..𪛟
    {0x2A700, 0x2B738, 15}, // Han 𪜀..𫜸
    {0x2B740, 0x2B81D, 15}, // Han 𫝀..𫠝
    {0x2B820, 0x2CEA1, 15}, // Han 𫠠..𬺡
    {0x2CEB0, 0x2EBE0, 15}, // Han 𬺰..𮯠
    {0x30000, 0x3134A, 15}, // Han 𰀀..𱍊
};
// 315 ranges, 114 singles, 93036 codepoints

// Filtering allowed scripts, XID_Continue,!XID_Start, Skipped Ids, NFC and !MARK
const struct sc safec23_cont_list[] = {
    {0x30, 0x39, 0}, // Common 0..9
    {0x5F, 0x5F, 0}, // Common _
    {0xB7, 0xB7, 0}, // Common ·
    {0x660, 0x669, 3}, // Arabic ٠..٩
    {0x6F0, 0x6F9, 3}, // Arabic ۰..۹
    {0x966, 0x96F, 8}, // Devanagari ०..९
    {0x9E6, 0x9EF, 5}, // Bengali ০..৯
    {0xA66, 0xA6F, 13}, // Gurmukhi ੦..੯
    {0xAE6, 0xAEF, 12}, // Gujarati ૦..૯
    {0xB66, 0xB6F, 24}, // Oriya ୦..୯
    {0xBE6, 0xBEF, 26}, // Tamil ௦..௯
    {0xC66, 0xC6F, 27}, // Telugu ౦..౯
    {0xCE6, 0xCEF, 19}, // Kannada ೦..೯
    {0xD66, 0xD6F, 22}, // Malayalam ൦..൯
    {0xE33, 0xE33, 29}, // Thai ำ
    {0xE50, 0xE59, 29}, // Thai ๐..๙
    {0xEB3, 0xEB3, 21}, // Lao ຳ
    {0xED0, 0xED9, 21}, // Lao ໐..໙
    {0xF20, 0xF29, 30}, // Tibetan ༠..༩
    {0x1040, 0x1049, 23}, // Myanmar ၀..၉
    {0x1090, 0x1099, 23}, // Myanmar ႐..႙
    {0x17E0, 0x17E9, 20}, // Khmer ០..៩
    {0x203F, 0x2040, 0}, // Common ‿..⁀
    {0xA9F0, 0xA9F9, 23}, // Myanmar ꧰..꧹
    {0xFE33, 0xFE34, 0}, // Common ︳..︴
    {0xFE4D, 0xFE4F, 0}, // Common ﹍..﹏
    {0xFF10, 0xFF19, 0}, // Common ０..９
    {0xFF3F, 0xFF3F, 0}, // Common ＿
    {0xFF9E, 0xFF9F, 0}, // Common ﾞ..ﾟ
    {0x1D7CE, 0x1D7FF, 0}, // Common 𝟎..𝟿
    {0x1FBF0, 0x1FBF9, 0}, // Common 🯰..🯹
};
// 26 ranges, 5 singles, 243 codepoints


//---------------------------------------------------

// Only excluded scripts, XID_Start,!Obsolete,!Uncommon_Use, NFC and !MARK
const struct sc safec23_excl_start_list[] = {
    {0x3E2, 0x3EF, 43}, // Coptic (Excluded) Ϣ..ϯ
    {0x800, 0x815, 107}, // Samaritan (Excluded) ࠀ..ࠕ
    {0x81A, 0x81A, 107}, // Samaritan (Excluded) ࠚ
    {0x824, 0x824, 107}, // Samaritan (Excluded) ࠤ
    {0x828, 0x828, 107}, // Samaritan (Excluded) ࠨ
    {0x1681, 0x169A, 88}, // Ogham (Excluded) ᚁ..ᚚ
    {0x16A0, 0x16EA, 106}, // Runic (Excluded) ᚠ..ᛪ
    {0x16EE, 0x16F8, 106}, // Runic (Excluded) ᛮ..ᛸ
    {0x1700, 0x1711, 115}, // Tagalog (Excluded) ᜀ..ᜑ
    {0x171F, 0x171F, 115}, // Tagalog (Excluded) ᜟ
    {0x1721, 0x1731, 58}, // Hanunoo (Excluded) ᜡ..ᜱ
    {0x1740, 0x1751, 39}, // Buhid (Excluded) ᝀ..ᝑ
    {0x1760, 0x176C, 116}, // Tagbanwa (Excluded) ᝠ..ᝬ
    {0x176E, 0x1770, 116}, // Tagbanwa (Excluded) ᝮ..ᝰ
    {0x1820, 0x1878, 82}, // Mongolian (Excluded) ᠠ..ᡸ
    {0x1880, 0x1884, 82}, // Mongolian (Excluded) ᢀ..ᢄ
    {0x1887, 0x18A8, 82}, // Mongolian (Excluded) ᢇ..ᢨ
    {0x18AA, 0x18AA, 82}, // Mongolian (Excluded) ᢪ
    {0x1A00, 0x1A16, 38}, // Buginese (Excluded) ᨀ..ᨖ
    {0x1CFA, 0x1CFA, 86}, // Nandinagari (Excluded) ᳺ
    {0x2C00, 0x2C5F, 54}, // Glagolitic (Excluded) Ⰰ..ⱟ
    {0x2C80, 0x2CE4, 43}, // Coptic (Excluded) Ⲁ..ⳤ
    {0x2CEB, 0x2CEE, 43}, // Coptic (Excluded) Ⳬ..ⳮ
    {0x2CF2, 0x2CF3, 43}, // Coptic (Excluded) Ⳳ..ⳳ
    {0xA840, 0xA873, 102}, // Phags_Pa (Excluded) ꡀ..ꡳ
    {0xA930, 0xA946, 105}, // Rejang (Excluded) ꤰ..ꥆ
    {0x10000, 0x1000B, 69}, // Linear_B (Excluded) 𐀀..𐀋
    {0x1000D, 0x10026, 69}, // Linear_B (Excluded) 𐀍..𐀦
    {0x10028, 0x1003A, 69}, // Linear_B (Excluded) 𐀨..𐀺
    {0x1003C, 0x1003D, 69}, // Linear_B (Excluded) 𐀼..𐀽
    {0x1003F, 0x1004D, 69}, // Linear_B (Excluded) 𐀿..𐁍
    {0x10050, 0x1005D, 69}, // Linear_B (Excluded) 𐁐..𐁝
    {0x10080, 0x100FA, 69}, // Linear_B (Excluded) 𐂀..𐃺
    {0x10280, 0x1029C, 70}, // Lycian (Excluded) 𐊀..𐊜
    {0x102A0, 0x102D0, 40}, // Carian (Excluded) 𐊠..𐋐
    {0x10300, 0x1031F, 90}, // Old_Italic (Excluded) 𐌀..𐌟
    {0x1032D, 0x1032F, 90}, // Old_Italic (Excluded) 𐌭..𐌯
    {0x10331, 0x1034A, 55}, // Gothic (Excluded) 𐌱..𐍊
    {0x10350, 0x10375, 92}, // Old_Permic (Excluded) 𐍐..𐍵
    {0x10380, 0x1039D, 122}, // Ugaritic (Excluded) 𐎀..𐎝
    {0x103A0, 0x103C3, 93}, // Old_Persian (Excluded) 𐎠..𐏃
    {0x103C8, 0x103CF, 93}, // Old_Persian (Excluded) 𐏈..𐏏
    {0x103D1, 0x103D5, 93}, // Old_Persian (Excluded) 𐏑..𐏕
    {0x10400, 0x1044F, 47}, // Deseret (Excluded) 𐐀..𐑏
    {0x10451, 0x1047F, 109}, // Shavian (Excluded) 𐑑..𐑿
    {0x10481, 0x1049D, 98}, // Osmanya (Excluded) 𐒁..𐒝
    {0x10500, 0x10527, 52}, // Elbasan (Excluded) 𐔀..𐔧
    {0x10530, 0x10563, 41}, // Caucasian_Albanian (Excluded) 𐔰..𐕣
    {0x10570, 0x1057A, 123}, // Vithkuqi (Excluded) 𐕰..𐕺
    {0x1057C, 0x1058A, 123}, // Vithkuqi (Excluded) 𐕼..𐖊
    {0x1058C, 0x10592, 123}, // Vithkuqi (Excluded) 𐖌..𐖒
    {0x10594, 0x10595, 123}, // Vithkuqi (Excluded) 𐖔..𐖕
    {0x10597, 0x105A1, 123}, // Vithkuqi (Excluded) 𐖗..𐖡
    {0x105A3, 0x105B1, 123}, // Vithkuqi (Excluded) 𐖣..𐖱
    {0x105B3, 0x105B9, 123}, // Vithkuqi (Excluded) 𐖳..𐖹
    {0x105BB, 0x105BC, 123}, // Vithkuqi (Excluded) 𐖻..𐖼
    {0x10600, 0x10736, 68}, // Linear_A (Excluded) 𐘀..𐜶
    {0x10740, 0x10755, 68}, // Linear_A (Excluded) 𐝀..𐝕
    {0x10760, 0x10767, 68}, // Linear_A (Excluded) 𐝠..𐝧
    {0x10800, 0x10805, 45}, // Cypriot (Excluded) 𐠀..𐠅
    {0x10808, 0x10808, 45}, // Cypriot (Excluded) 𐠈
    {0x1080A, 0x10835, 45}, // Cypriot (Excluded) 𐠊..𐠵
    {0x10837, 0x10838, 45}, // Cypriot (Excluded) 𐠷..𐠸
    {0x1083C, 0x1083C, 45}, // Cypriot (Excluded) 𐠼
    {0x1083F, 0x1083F, 45}, // Cypriot (Excluded) 𐠿
    {0x10841, 0x10855, 60}, // Imperial_Aramaic (Excluded) 𐡁..𐡕
    {0x10860, 0x10876, 100}, // Palmyrene (Excluded) 𐡠..𐡶
    {0x10880, 0x1089E, 85}, // Nabataean (Excluded) 𐢀..𐢞
    {0x108E0, 0x108F2, 59}, // Hatran (Excluded) 𐣠..𐣲
    {0x108F4, 0x108F5, 59}, // Hatran (Excluded) 𐣴..𐣵
    {0x10900, 0x10915, 103}, // Phoenician (Excluded) 𐤀..𐤕
    {0x10920, 0x10939, 71}, // Lydian (Excluded) 𐤠..𐤹
    {0x10980, 0x1099F, 80}, // Meroitic_Hieroglyphs (Excluded) 𐦀..𐦟
    {0x109A1, 0x109B7, 79}, // Meroitic_Cursive (Excluded) 𐦡..𐦷
    {0x109BE, 0x109BF, 79}, // Meroitic_Cursive (Excluded) 𐦾..𐦿
    {0x10A00, 0x10A00, 64}, // Kharoshthi (Excluded) 𐨀
    {0x10A10, 0x10A13, 64}, // Kharoshthi (Excluded) 𐨐..𐨓
    {0x10A15, 0x10A17, 64}, // Kharoshthi (Excluded) 𐨕..𐨗
    {0x10A19, 0x10A35, 64}, // Kharoshthi (Excluded) 𐨙..𐨵
    {0x10A60, 0x10A7C, 95}, // Old_South_Arabian (Excluded) 𐩠..𐩼
    {0x10A80, 0x10A9C, 91}, // Old_North_Arabian (Excluded) 𐪀..𐪜
    {0x10AC0, 0x10AC7, 74}, // Manichaean (Excluded) 𐫀..𐫇
    {0x10AC9, 0x10AE4, 74}, // Manichaean (Excluded) 𐫉..𐫤
    {0x10B00, 0x10B35, 33}, // Avestan (Excluded) 𐬀..𐬵
    {0x10B40, 0x10B55, 62}, // Inscriptional_Parthian (Excluded) 𐭀..𐭕
    {0x10B60, 0x10B72, 61}, // Inscriptional_Pahlavi (Excluded) 𐭠..𐭲
    {0x10B80, 0x10B91, 104}, // Psalter_Pahlavi (Excluded) 𐮀..𐮑
    {0x10C00, 0x10C48, 96}, // Old_Turkic (Excluded) 𐰀..𐱈
    {0x10C80, 0x10CB2, 89}, // Old_Hungarian (Excluded) 𐲀..𐲲
    {0x10CC0, 0x10CF2, 89}, // Old_Hungarian (Excluded) 𐳀..𐳲
    {0x10E80, 0x10EA9, 125}, // Yezidi (Excluded) 𐺀..𐺩
    {0x10EB0, 0x10EB1, 125}, // Yezidi (Excluded) 𐺰..𐺱
    {0x10F00, 0x10F1C, 94}, // Old_Sogdian (Excluded) 𐼀..𐼜
    {0x10F27, 0x10F27, 94}, // Old_Sogdian (Excluded) 𐼧
    {0x10F30, 0x10F45, 112}, // Sogdian (Excluded) 𐼰..𐽅
    {0x10F70, 0x10F81, 97}, // Old_Uyghur (Excluded) 𐽰..𐾁
    {0x10FB0, 0x10FC4, 42}, // Chorasmian (Excluded) 𐾰..𐿄
    {0x10FE0, 0x10FF6, 53}, // Elymaic (Excluded) 𐿠..𐿶
    {0x11003, 0x11037, 36}, // Brahmi (Excluded) 𑀃..𑀷
    {0x11071, 0x11072, 36}, // Brahmi (Excluded) 𑁱..𑁲
    {0x11075, 0x11075, 36}, // Brahmi (Excluded) 𑁵
    {0x11083, 0x110AF, 63}, // Kaithi (Excluded) 𑂃..𑂯
    {0x110D0, 0x110E8, 113}, // Sora_Sompeng (Excluded) 𑃐..𑃨
    {0x11150, 0x11172, 72}, // Mahajani (Excluded) 𑅐..𑅲
    {0x11176, 0x11176, 72}, // Mahajani (Excluded) 𑅶
    {0x11183, 0x111B2, 108}, // Sharada (Excluded) 𑆃..𑆲
    {0x111C1, 0x111C4, 108}, // Sharada (Excluded) 𑇁..𑇄
    {0x111DA, 0x111DA, 108}, // Sharada (Excluded) 𑇚
    {0x111DC, 0x111DC, 108}, // Sharada (Excluded) 𑇜
    {0x11200, 0x11211, 66}, // Khojki (Excluded) 𑈀..𑈑
    {0x11213, 0x1122B, 66}, // Khojki (Excluded) 𑈓..𑈫
    {0x11280, 0x11286, 84}, // Multani (Excluded) 𑊀..𑊆
    {0x11288, 0x11288, 84}, // Multani (Excluded) 𑊈
    {0x1128A, 0x1128D, 84}, // Multani (Excluded) 𑊊..𑊍
    {0x1128F, 0x1129D, 84}, // Multani (Excluded) 𑊏..𑊝
    {0x1129F, 0x112A8, 84}, // Multani (Excluded) 𑊟..𑊨
    {0x112B0, 0x112DE, 67}, // Khudawadi (Excluded) 𑊰..𑋞
    {0x11305, 0x1130C, 56}, // Grantha (Excluded) 𑌅..𑌌
    {0x1130F, 0x11310, 56}, // Grantha (Excluded) 𑌏..𑌐
    {0x11313, 0x11328, 56}, // Grantha (Excluded) 𑌓..𑌨
    {0x1132A, 0x11330, 56}, // Grantha (Excluded) 𑌪..𑌰
    {0x11332, 0x11333, 56}, // Grantha (Excluded) 𑌲..𑌳
    {0x11335, 0x11339, 56}, // Grantha (Excluded) 𑌵..𑌹
    {0x1133D, 0x1133D, 56}, // Grantha (Excluded) 𑌽
    {0x11350, 0x11350, 56}, // Grantha (Excluded) 𑍐
    {0x1135D, 0x11361, 56}, // Grantha (Excluded) 𑍝..𑍡
    {0x11480, 0x114AF, 120}, // Tirhuta (Excluded) 𑒀..𑒯
    {0x114C4, 0x114C5, 120}, // Tirhuta (Excluded) 𑓄..𑓅
    {0x114C7, 0x114C7, 120}, // Tirhuta (Excluded) 𑓇
    {0x11580, 0x115AE, 110}, // Siddham (Excluded) 𑖀..𑖮
    {0x115D8, 0x115DB, 110}, // Siddham (Excluded) 𑗘..𑗛
    {0x11600, 0x1162F, 81}, // Modi (Excluded) 𑘀..𑘯
    {0x11644, 0x11644, 81}, // Modi (Excluded) 𑙄
    {0x11680, 0x116AA, 117}, // Takri (Excluded) 𑚀..𑚪
    {0x116B8, 0x116B8, 117}, // Takri (Excluded) 𑚸
    {0x11700, 0x1171A, 31}, // Ahom (Excluded) 𑜀..𑜚
    {0x11740, 0x11746, 31}, // Ahom (Excluded) 𑝀..𑝆
    {0x11800, 0x1182B, 49}, // Dogra (Excluded) 𑠀..𑠫
    {0x118A0, 0x118DF, 124}, // Warang_Citi (Excluded) 𑢠..𑣟
    {0x118FF, 0x118FF, 124}, // Warang_Citi (Excluded) 𑣿
    {0x11901, 0x11906, 48}, // Dives_Akuru (Excluded) 𑤁..𑤆
    {0x11909, 0x11909, 48}, // Dives_Akuru (Excluded) 𑤉
    {0x1190C, 0x11913, 48}, // Dives_Akuru (Excluded) 𑤌..𑤓
    {0x11915, 0x11916, 48}, // Dives_Akuru (Excluded) 𑤕..𑤖
    {0x11918, 0x1192F, 48}, // Dives_Akuru (Excluded) 𑤘..𑤯
    {0x1193F, 0x1193F, 48}, // Dives_Akuru (Excluded) 𑤿
    {0x11941, 0x11941, 48}, // Dives_Akuru (Excluded) 𑥁
    {0x119A0, 0x119A7, 86}, // Nandinagari (Excluded) 𑦠..𑦧
    {0x119AA, 0x119D0, 86}, // Nandinagari (Excluded) 𑦪..𑧐
    {0x119E1, 0x119E1, 86}, // Nandinagari (Excluded) 𑧡
    {0x119E3, 0x119E3, 86}, // Nandinagari (Excluded) 𑧣
    {0x11A00, 0x11A00, 126}, // Zanabazar_Square (Excluded) 𑨀
    {0x11A0B, 0x11A32, 126}, // Zanabazar_Square (Excluded) 𑨋..𑨲
    {0x11A3A, 0x11A3A, 126}, // Zanabazar_Square (Excluded) 𑨺
    {0x11A50, 0x11A50, 114}, // Soyombo (Excluded) 𑩐
    {0x11A5C, 0x11A89, 114}, // Soyombo (Excluded) 𑩜..𑪉
    {0x11A9D, 0x11A9D, 114}, // Soyombo (Excluded) 𑪝
    {0x11AC0, 0x11AF8, 101}, // Pau_Cin_Hau (Excluded) 𑫀..𑫸
    {0x11C00, 0x11C08, 35}, // Bhaiksuki (Excluded) 𑰀..𑰈
    {0x11C0A, 0x11C2E, 35}, // Bhaiksuki (Excluded) 𑰊..𑰮
    {0x11C40, 0x11C40, 35}, // Bhaiksuki (Excluded) 𑱀
    {0x11C72, 0x11C8F, 75}, // Marchen (Excluded) 𑱲..𑲏
    {0x11D00, 0x11D06, 76}, // Masaram_Gondi (Excluded) 𑴀..𑴆
    {0x11D08, 0x11D09, 76}, // Masaram_Gondi (Excluded) 𑴈..𑴉
    {0x11D0B, 0x11D30, 76}, // Masaram_Gondi (Excluded) 𑴋..𑴰
    {0x11D46, 0x11D46, 76}, // Masaram_Gondi (Excluded) 𑵆
    {0x11EE0, 0x11EF2, 73}, // Makasar (Excluded) 𑻠..𑻲
    {0x12000, 0x12399, 44}, // Cuneiform (Excluded) 𒀀..𒎙
    {0x12400, 0x1246E, 44}, // Cuneiform (Excluded) 𒐀..𒑮
    {0x12480, 0x12543, 44}, // Cuneiform (Excluded) 𒒀..𒕃
    {0x12F90, 0x12FF0, 46}, // Cypro_Minoan (Excluded) 𒾐..𒿰
    {0x13000, 0x1342E, 51}, // Egyptian_Hieroglyphs (Excluded) 𓀀..𓐮
    {0x14400, 0x14646, 32}, // Anatolian_Hieroglyphs (Excluded) 𔐀..𔙆
    {0x16A70, 0x16ABE, 118}, // Tangsa (Excluded) 𖩰..𖪾
    {0x16AD0, 0x16AED, 34}, // Bassa_Vah (Excluded) 𖫐..𖫭
    {0x16B00, 0x16B2F, 99}, // Pahawh_Hmong (Excluded) 𖬀..𖬯
    {0x16B40, 0x16B43, 99}, // Pahawh_Hmong (Excluded) 𖭀..𖭃
    {0x16B63, 0x16B77, 99}, // Pahawh_Hmong (Excluded) 𖭣..𖭷
    {0x16B7D, 0x16B8F, 99}, // Pahawh_Hmong (Excluded) 𖭽..𖮏
    {0x16E40, 0x16E7F, 77}, // Medefaidrin (Excluded) 𖹀..𖹿
    {0x16FE0, 0x16FE0, 119}, // Tangut (Excluded) 𖿠
    {0x17000, 0x187F7, 119}, // Tangut (Excluded) 𗀀..𘟷
    {0x18800, 0x18AFF, 119}, // Tangut (Excluded) 𘠀..𘫿
    {0x18B01, 0x18CD5, 65}, // Khitan_Small_Script (Excluded) 𘬁..𘳕
    {0x18D00, 0x18D08, 119}, // Tangut (Excluded) 𘴀..𘴈
    {0x1B170, 0x1B2FB, 87}, // Nushu (Excluded) 𛅰..𛋻
    {0x1BC00, 0x1BC6A, 50}, // Duployan (Excluded) 𛰀..𛱪
    {0x1BC70, 0x1BC7C, 50}, // Duployan (Excluded) 𛱰..𛱼
    {0x1BC80, 0x1BC88, 50}, // Duployan (Excluded) 𛲀..𛲈
    {0x1BC90, 0x1BC99, 50}, // Duployan (Excluded) 𛲐..𛲙
    {0x1E290, 0x1E2AD, 121}, // Toto (Excluded) 𞊐..𞊭
    {0x1E800, 0x1E8C4, 78}, // Mende_Kikakui (Excluded) 𞠀..𞣄
};
// 158 ranges, 34 singles, 14926 codepoints

// Only excluded scripts, XID_Continue,!XID_Start, Skipped Ids, NFC and !MARK
const struct range_bool safec23_excl_cont_list[] = {
    {0x1810, 0x1819, 82}, // Mongolian (Excluded) ᠐..᠙
    {0x104A0, 0x104A9, 98}, // Osmanya (Excluded) 𐒠..𐒩
    {0x11066, 0x1106F, 36}, // Brahmi (Excluded) 𑁦..𑁯
    {0x110F0, 0x110F9, 113}, // Sora_Sompeng (Excluded) 𑃰..𑃹
    {0x111D0, 0x111D9, 108}, // Sharada (Excluded) 𑇐..𑇙
    {0x112F0, 0x112F9, 67}, // Khudawadi (Excluded) 𑋰..𑋹
    {0x114D0, 0x114D9, 120}, // Tirhuta (Excluded) 𑓐..𑓙
    {0x11650, 0x11659, 81}, // Modi (Excluded) 𑙐..𑙙
    {0x116C0, 0x116C9, 117}, // Takri (Excluded) 𑛀..𑛉
    {0x11730, 0x11739, 31}, // Ahom (Excluded) 𑜰..𑜹
    {0x118E0, 0x118E9, 124}, // Warang_Citi (Excluded) 𑣠..𑣩
    {0x11950, 0x11959, 48}, // Dives_Akuru (Excluded) 𑥐..𑥙
    {0x11C50, 0x11C59, 35}, // Bhaiksuki (Excluded) 𑱐..𑱙
    {0x11D50, 0x11D59, 76}, // Masaram_Gondi (Excluded) 𑵐..𑵙
    {0x16AC0, 0x16AC9, 118}, // Tangsa (Excluded) 𖫀..𖫉
    {0x16B50, 0x16B59, 99}, // Pahawh_Hmong (Excluded) 𖭐..𖭙
};
// 16 ranges, 0 singles, 144 codepoints
