#!/usr/bin/env perl
# libu8ident - Check unicode security guidelines for identifiers.
# Copyright 2026 Reini Urban
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
#
# Create u8idcasefold.h: simple Unicode case folding table for
# U8ID_FOLDCASE, from CaseFolding.txt status C (common) and S (simple)
# mappings. F (full, multi-codepoint) and T (Turkic-locale-specific)
# mappings are intentionally excluded: this library only ever folds a
# single codepoint to a single codepoint, so string length never
# changes and no locale is involved.

use strict;
use warnings;
use Config;

my $cf_h = "u8idcasefold.h";
my $ucd = "CaseFolding.txt";
if (!-e $ucd) {
  system("wget -N https://www.unicode.org/Public/UNIDATA/$ucd");
  if (!-e $ucd && -e $cf_h) {
    die "Cannot download $ucd, but have $cf_h\n";
  }
}

my @fold; # [cp, folded]
open my $UCD, "<", $ucd or die "$ucd $!";
while (<$UCD>) {
  next if /^#/ or /^\s*$/;
  # 0041; C; 0061; # LATIN CAPITAL LETTER A
  my ($cp, $status, $mapping) = split /;\s*/, $_;
  next unless defined $status;
  next unless $status eq 'C' || $status eq 'S';
  push @fold, [hex($cp), hex($mapping)];
}
close $UCD;
@fold = sort { $a->[0] <=> $b->[0] } @fold;

if (!-w $cf_h && -e $cf_h) {
  chmod 0644, $cf_h;
}
open my $H, ">", $cf_h or die "writing $cf_h $!";
print $H <<'EOF';
/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- */
/* libu8ident - Check unicode security guidelines for identifiers.
   Copyright 2026 Reini Urban
   SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

   Simple Unicode case folding table, for U8ID_FOLDCASE.
   From CaseFolding.txt, status C (common) + S (simple) mappings
   only: every entry maps exactly one codepoint to exactly one
   codepoint (no full/multi-codepoint F mappings, no locale-specific
   T mappings).
   Generated by mkcasefold.pl, do not modify.
*/

#include <stdint.h>

struct u8id_casefold {
  uint32_t cp;
  uint32_t folded;
};

EOF
printf $H "#define U8ID_CASEFOLD_SIZE %u\n\n", scalar @fold;
print $H "static const struct u8id_casefold u8id_casefold_tbl[U8ID_CASEFOLD_SIZE] = {\n";
print $H "    // clang-format off\n";
my $i = 0;
for my $e (@fold) {
  printf $H "    {0x%X, 0x%X},", $e->[0], $e->[1];
  $i++;
  print $H ($i % 4 == 0) ? "\n" : " ";
}
print $H "\n" if $i % 4 != 0;
print $H "    // clang-format on\n";
print $H "};\n";
close $H;
chmod 0444, $cf_h;
print "Created $cf_h\n";
