/* libu8ident - Check unicode security guidelines for identifiers.
   Copyright 2021 Reini Urban
   SPDX-License-Identifier: Apache-2.0

   generated by hand from
   http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2731.pdf

   N2731 Annex D (normative) (starting with C11 N1570)
   Universal character names for identifiers
   This clause lists the hexadecimal code values that are valid in universal
   character names in identifiers.

   D.1 Ranges of characters allowed

   00A8, 00AA, 00AD, 00AF, 00B2–00B5, 00B7–00BA, 00BC–00BE, 00C0–00D6,
   00D8–00F6, 00F8–00FF 0100–167F, 1681–180D, 180F–1FFF 200B–200D, 202A–202E,
   203F–2040, 2054, 2060–206F 2070–218F, 2460–24FF, 2776–2793, 2C00–2DFF,
   2E80–2FFF 3004–3007, 3021–302F, 3031–303F 3040–D7FF F900–FD3D, FD40–FDCF,
   FDF0–FE44, FE47–FFFD 10000–1FFFD, 20000–2FFFD, 30000–3FFFD, 40000–4FFFD,
   50000–5FFFD, 60000–6FFFD, 70000– 7FFFD, 80000–8FFFD, 90000–9FFFD,
   A0000–AFFFD, B0000–BFFFD, C0000–CFFFD, D0000–DFFFD, E0000–EFFFD

   D.2 Ranges of characters disallowed initially

   0300–036F, 1DC0–1DFF, 20D0–20FF, FE20–FE2F
*/

#ifdef EXT_SCRIPTS
extern const struct range_bool c11_start_list[53];
extern const struct range_bool c11_cont_list[6];
#else
// scripts generated by test-c11
const struct range_bool c11_start_list[] = {
    {'$', '$'},
    {'A', 'Z'},
    {'_', '_'},
    {'a', 'z'},
    {0x00A8, 0x00A8},   {0x00AA, 0x00AA},
    {0x00AD, 0x00AD},   {0x00AF, 0x00AF},   {0x00B2, 0x00B5},
    {0x00B7, 0x00BA},   {0x00BC, 0x00BE},   {0x00C0, 0x00D6},
    {0x00D8, 0x00F6},   {0x00F8, 0x00FF},
    {0x0100, 0x02FF}, // Latin, 2EA: Bopomofo
    {0x370, 0x167F},  // Greek
                      // 3E2: Coptic (Excluded)
                      // 3F0: Greek
                      // 400: Cyrillic
                      // 531: Armenian
                      // 591: Hebrew
                      // 600: Arabic
                      // 700: Syriac (Limited)
                      // 750: Arabic
                      // 780: Thaana
                      // 7C0: Nko (Limited)
                      // 800: Samaritan (Excluded)
                      // 840: Mandaic (Limited)
                      // 860: Syriac (Limited)
                      // 870: Arabic
                      // 900: Devanagari
                      // 980: Bengali
                      // A01: Gurmukhi
                      // A81: Gujarati
                      // B01: Oriya
                      // B82: Tamil
                      // C00: Telugu
                      // C80: Kannada
                      // D00: Malayalam
                      // D81: Sinhala
                      // E01: Thai
                      // E81: Lao
                      // F00: Tibetan
                      // 1000: Myanmar
                      // 10A0: Georgian
                      // 1100: Hangul
                      // 1200: Ethiopic
                      // 13A0: Cherokee (Limited)
                      // 1400: Canadian_Aboriginal (Limited)
    {0x1681, 0x180D}, // Ogham (Excluded)
                      // 16A0: Runic (Excluded)
                      // 1700: Tagalog (Excluded)
                      // 1720: Hanunoo (Excluded)
                      // 1740: Buhid (Excluded)
                      // 1760: Tagbanwa (Excluded)
                      // 1780: Khmer
                      // 1800: Mongolian (Excluded)
    {0x180F, 0x1DBF}, // 18B0: Canadian_Aboriginal (Limited)
                      // 1900: Limbu (Limited)
                      // 1950: Tai_Le (Limited)
                      // 1980: New_Tai_Lue (Limited)
                      // 19E0: Khmer
                      // 1A00: Buginese (Excluded)
                      // 1A20: Tai_Tham (Limited)
                      // 1B00: Balinese (Limited)
                      // 1B80: Sundanese (Limited)
                      // 1BC0: Batak (Limited)
                      // 1C00: Lepcha (Limited)
                      // 1C50: Ol_Chiki (Limited)
                      // 1C80: Cyrillic
                      // 1C90: Georgian
                      // 1CC0: Sundanese (Limited)
                      // 1D26: Greek
                      // 1D2B: Cyrillic
                      // 1D5D: Greek
                      // 1D78: Cyrillic
                      // 1DBF: Greek
    {0x1E00, 0x1FFF}, // Latin, Greek
    {0x200B, 0x200D}, // ZERO WIDTH Cf !!!
    {0x202A, 0x202E}, // RTL, LTR backdoors !!!
    {0x203F, 0x2040}, // UNDERTIE;Pc
    {0x2054, 0x2054}, // INVERTED UNDERTIE;Pc
    {0x2060, 0x206F}, // WORD JOINER;Cf, INVISIBLE SEPARATOR;Cf, LTR, RTL backdoors, ... !!! 
    {0x2070, 0x20CF}, // SUPER/SUBSCRIPTS
    {0x2100, 0x218F}, // Math Symbols
    {0x2460, 0x24FF}, // Circled Digit,Letters,...
    {0x2776, 0x2793}, //   -"-
    {0x2C00, 0x2DFF}, // Glagolitic (Excluded)
                      // 2C80: Coptic (Excluded)
                      // 2D00: Georgian
                      // 2D30: Tifinagh (Limited)
                      // 2D80: Ethiopic
                      // 2DE0: Cyrillic
    {0x2E80, 0x2FFF}, // Han
    {0x3004, 0x3007}, // Japanese Symbols
    {0x3021, 0x302F}, // 302E: Hangul
    {0x3031, 0x303F}, // 3038: Han
    {0x3040, 0xD7FF}, // 3041: Hiragana
                      // 30A1: Katakana
                      // 3105: Bopomofo
                      // 3131: Hangul
                      // 31A0: Bopomofo
                      // 31F0: Katakana
                      // 3200: Hangul
                      // 32D0: Katakana
                      // 3400: Han
                      // A000: Yi (Limited)
                      // A4D0: Lisu (Limited)
                      // A500: Vai (Limited)
                      // A640: Cyrillic
                      // A6A0: Bamum (Limited)
                      // A800: Syloti_Nagri (Limited)
                      // A840: Phags_Pa (Excluded)
                      // A880: Saurashtra (Limited)
                      // A8E0: Devanagari
                      // A900: Kayah_Li (Limited)
                      // A930: Rejang (Excluded)
                      // A960: Hangul
                      // A980: Javanese (Limited)
                      // A9E0: Myanmar
                      // AA00: Cham (Limited)
                      // AA60: Myanmar
                      // AA80: Tai_Viet (Limited)
                      // AAE0: Meetei_Mayek (Limited)
                      // AB01: Ethiopic
                      // AB65: Greek
                      // AB70: Cherokee (Limited)
                      // ABC0: Meetei_Mayek (Limited)
                      // AC00: Hangul
    {0xF900, 0xFD3D}, // Han
                      // FB13: Armenian
                      // FB1D: Hebrew
                      // FB50: Arabic
    {0xFD40, 0xFDCF},
                      // FDD0-FDEF is unassigned
    {0xFDF0, 0xFE1F},
    {0xFE30, 0xFE44},
    {0xFE47, 0xFFFD}, // FF66: Katakana
                      // FFA0: Hangul
    {0x10000, 0x1FFFD}, // Linear_B (Excluded)
                      // 10140: Greek
                      // 10280: Lycian (Excluded)
                      // 102A0: Carian (Excluded)
                      // 10300: Old_Italic (Excluded)
                      // 10330: Gothic (Excluded)
                      // 10350: Old_Permic (Excluded)
                      // 10380: Ugaritic (Excluded)
                      // 103A0: Old_Persian (Excluded)
                      // 10400: Deseret (Excluded)
                      // 10450: Shavian (Excluded)
                      // 10480: Osmanya (Excluded)
                      // 104B0: Osage (Limited)
                      // 10500: Elbasan (Excluded)
                      // 10530: Caucasian_Albanian (Excluded)
                      // 10570: Vithkuqi (Excluded)
                      // 10600: Linear_A (Excluded)
                      // 10800: Cypriot (Excluded)
                      // 10840: Imperial_Aramaic (Excluded)
                      // 10860: Palmyrene (Excluded)
                      // 10880: Nabataean (Excluded)
                      // 108E0: Hatran (Excluded)
                      // 10900: Phoenician (Excluded)
                      // 10920: Lydian (Excluded)
                      // 10980: Meroitic_Hieroglyphs (Excluded)
                      // 109A0: Meroitic_Cursive (Excluded)
                      // 10A00: Kharoshthi (Excluded)
                      // 10A60: Old_South_Arabian (Excluded)
                      // 10A80: Old_North_Arabian (Excluded)
                      // 10AC0: Manichaean (Excluded)
                      // 10B00: Avestan (Excluded)
                      // 10B40: Inscriptional_Parthian (Excluded)
                      // 10B60: Inscriptional_Pahlavi (Excluded)
                      // 10B80: Psalter_Pahlavi (Excluded)
                      // 10C00: Old_Turkic (Excluded)
                      // 10C80: Old_Hungarian (Excluded)
                      // 10D00: Hanifi_Rohingya (Limited)
                      // 10E60: Arabic
                      // 10E80: Yezidi (Excluded)
                      // 10F00: Old_Sogdian (Excluded)
                      // 10F30: Sogdian (Excluded)
                      // 10F70: Old_Uyghur (Excluded)
                      // 10FB0: Chorasmian (Excluded)
                      // 10FE0: Elymaic (Excluded)
                      // 11000: Brahmi (Excluded)
                      // 11080: Kaithi (Excluded)
                      // 110D0: Sora_Sompeng (Excluded)
                      // 11100: Chakma (Limited)
                      // 11150: Mahajani (Excluded)
                      // 11180: Sharada (Excluded)
                      // 111E1: Sinhala
                      // 11200: Khojki (Excluded)
                      // 11280: Multani (Excluded)
                      // 112B0: Khudawadi (Excluded)
                      // 11300: Grantha (Excluded)
                      // 11400: Newa (Limited)
                      // 11480: Tirhuta (Excluded)
                      // 11580: Siddham (Excluded)
                      // 11600: Modi (Excluded)
                      // 11660: Mongolian (Excluded)
                      // 11680: Takri (Excluded)
                      // 11700: Ahom (Excluded)
                      // 11800: Dogra (Excluded)
                      // 118A0: Warang_Citi (Excluded)
                      // 11900: Dives_Akuru (Excluded)
                      // 119A0: Nandinagari (Excluded)
                      // 11A00: Zanabazar_Square (Excluded)
                      // 11A50: Soyombo (Excluded)
                      // 11AB0: Canadian_Aboriginal (Limited)
                      // 11AC0: Pau_Cin_Hau (Excluded)
                      // 11C00: Bhaiksuki (Excluded)
                      // 11C70: Marchen (Excluded)
                      // 11D00: Masaram_Gondi (Excluded)
                      // 11D60: Gunjala_Gondi (Excluded)
                      // 11EE0: Makasar (Excluded)
                      // 11FB0: Lisu (Limited)
                      // 11FC0: Tamil
                      // 12000: Cuneiform (Excluded)
                      // 12F90: Cypro_Minoan (Excluded)
                      // 13000: Egyptian_Hieroglyphs (Excluded)
                      // 14400: Anatolian_Hieroglyphs (Excluded)
                      // 16800: Bamum (Limited)
                      // 16A40: Mro (Excluded)
                      // 16A70: Tangsa (Excluded)
                      // 16AD0: Bassa_Vah (Excluded)
                      // 16B00: Pahawh_Hmong (Excluded)
                      // 16E40: Medefaidrin (Excluded)
                      // 16F00: Miao (Limited)
                      // 16FE0: Tangut (Excluded)
                      // 16FE1: Nushu (Excluded)
                      // 16FE2: Han
                      // 16FE4: Khitan_Small_Script (Excluded)
                      // 16FF0: Han
                      // 17000: Tangut (Excluded)
                      // 18B00: Khitan_Small_Script (Excluded)
                      // 18D00: Tangut (Excluded)
                      // 1AFF0: Katakana
                      // 1B001: Hiragana
                      // 1B120: Katakana
                      // 1B150: Hiragana
                      // 1B164: Katakana
                      // 1B170: Nushu (Excluded)
                      // 1BC00: Duployan (Excluded)
                      // 1D200: Greek
                      // 1D800: SignWriting (Excluded)
                      // 1E000: Glagolitic (Excluded)
                      // 1E100: Nyiakeng_Puachue_Hmong (Limited)
                      // 1E290: Toto (Excluded)
                      // 1E2C0: Wancho (Limited)
                      // 1E7E0: Ethiopic
                      // 1E800: Mende_Kikakui (Excluded)
                      // 1E900: Adlam (Limited)
                      // 1EE00: Arabic
                      // 1F200: Hiragana
    {0x20000, 0x2FFFD}, // Han
    {0x30000, 0x3FFFD},
    {0x40000, 0x4FFFD}, {0x50000, 0x5FFFD}, {0x60000, 0x6FFFD},
    {0x70000, 0x7FFFD}, {0x80000, 0x8FFFD}, {0x90000, 0x9FFFD},
    {0xA0000, 0xAFFFD}, {0xB0000, 0xBFFFD}, {0xC0000, 0xCFFFD},
    {0xD0000, 0xDFFFD}, {0xE0000, 0xEFFFD},
};

// plus these as cont (so Combining marks are allowed)
const struct range_bool c11_cont_list[] = {
    {'$', '$'},
    {'0', '9'},
    {0x0300, 0x036F}, // Latin Mn
    {0x1DC0, 0x1DFF}, // Greek, Latin, Devanagari + Cyrillic Mn
    {0x20D0, 0x20FF}, // ? Mn
    {0xFE20, 0xFE2F}, // ? Mn
};

#if 0
// Generated with test-c11 by filtering forbidden scripts.
// Use c11_cont_list with it.
// Rather see the better unic23.h, generated by mkc23
const struct range_bool safec23_start_list[] = {
    {'$', '$'},
    {'A', 'Z'},
    {'_', '_'},
    {'a', 'z'},
    {0x00A8, 0x00A8},   {0x00AA, 0x00AA},
    {0x00AD, 0x00AD},   {0x00AF, 0x00AF},   {0x00B2, 0x00B5},
    {0x00B7, 0x00BA},   {0x00BC, 0x00BE},   {0x00C0, 0x00D6},
    {0x00D8, 0x00F6},   {0x00F8, 0x00FF},
    // {0x0100, 0x02FF}, // Latin, 2B0-2FF: Modifiers, 2EA Bopomofo
    {0x100, 0x131}, // Latin
    {0x134, 0x13E}, // Latin
    {0x141, 0x148}, // Latin
    {0x14A, 0x17E}, // Latin
    {0x18F, 0x18F}, // Latin
    {0x1A0, 0x1A1}, // Latin
    {0x1AF, 0x1B0}, // Latin
    {0x1CD, 0x1DC}, // Latin
    {0x1DE, 0x1E3}, // Latin
    {0x1E6, 0x1F0}, // Latin
    {0x1F4, 0x1F5}, // Latin
    {0x1F8, 0x21B}, // Latin
    {0x21E, 0x21F}, // Latin
    {0x226, 0x233}, // Latin
    {0x259, 0x259}, // Latin
    {0x2BB, 0x2BC}, // Common
    {0x2EC, 0x2EC}, // Common
    {0x375, 0x375}, // Greek
    {0x37B, 0x37D}, // Greek
    {0x386, 0x386}, // Greek
    {0x388, 0x38A}, // Greek
    {0x38C, 0x38C}, // Greek
    {0x38E, 0x3A1}, // Greek
    {0x3A3, 0x3CE}, // Greek
    // skipped 0x3E2 Coptic (Excluded)
    {0x3FC, 0x45F}, // Greek
    {0x48A, 0x4FF}, // Cyrillic
    {0x510, 0x529}, // Cyrillic
    {0x52E, 0x52F}, // Cyrillic
    {0x531, 0x556}, // Armenian
    {0x559, 0x559}, // Armenian
    {0x561, 0x586}, // Armenian
    {0x58A, 0x58A}, // Armenian
    {0x5B4, 0x5B4}, // Hebrew
    {0x5D0, 0x5EA}, // Hebrew
    {0x5EF, 0x5F4}, // Hebrew
    {0x620, 0x63F}, // Arabic
    {0x641, 0x655}, // Arabic
    {0x660, 0x669}, // Arabic
    {0x670, 0x672}, // Inherited
    {0x674, 0x674}, // Arabic
    {0x679, 0x68D}, // Arabic
    {0x68F, 0x6A0}, // Arabic
    {0x6A2, 0x6D3}, // Arabic
    {0x6D5, 0x6D5}, // Arabic
    {0x6E5, 0x6E6}, // Arabic
    {0x6EE, 0x6FF}, // Arabic
    // skipped 0x700 Syriac (Limited)
    {0x750, 0x7B1}, // Thaana
    // skipped 0x7C0 Nko (Limited)
    // skipped 0x800 Samaritan (Excluded)
    // skipped 0x840 Mandaic (Limited)
    // skipped 0x860 Syriac (Limited)
    {0x870, 0x887}, // Arabic
    {0x889, 0x88E}, // Arabic
    {0x8A0, 0x8AC}, // Arabic
    {0x8B2, 0x8B2}, // Arabic
    {0x8B5, 0x8C9}, // Arabic
    {0x901, 0x94D}, // Devanagari
    {0x94F, 0x950}, // Devanagari
    {0x956, 0x957}, // Devanagari
    {0x960, 0x963}, // Devanagari
    {0x966, 0x96F}, // Devanagari
    {0x971, 0x977}, // Devanagari
    {0x979, 0x97F}, // Devanagari
    {0x981, 0x983}, // Bengali
    {0x985, 0x98C}, // Bengali
    {0x98F, 0x990}, // Bengali
    {0x993, 0x9A8}, // Bengali
    {0x9AA, 0x9B0}, // Bengali
    {0x9B2, 0x9B2}, // Bengali
    {0x9B6, 0x9B9}, // Bengali
    {0x9BC, 0x9C4}, // Bengali
    {0x9C7, 0x9C8}, // Bengali
    {0x9CB, 0x9CE}, // Bengali
    {0x9D7, 0x9D7}, // Bengali
    {0x9E0, 0x9E3}, // Bengali
    {0x9E6, 0x9F1}, // Bengali
    {0x9FE, 0x9FE}, // Bengali
    {0xA01, 0xA03}, // Gurmukhi
    {0xA05, 0xA0A}, // Gurmukhi
    {0xA0F, 0xA10}, // Gurmukhi
    {0xA13, 0xA28}, // Gurmukhi
    {0xA2A, 0xA30}, // Gurmukhi
    {0xA32, 0xA32}, // Gurmukhi
    {0xA35, 0xA35}, // Gurmukhi
    {0xA38, 0xA39}, // Gurmukhi
    {0xA3C, 0xA3C}, // Gurmukhi
    {0xA3E, 0xA42}, // Gurmukhi
    {0xA47, 0xA48}, // Gurmukhi
    {0xA4B, 0xA4D}, // Gurmukhi
    {0xA5C, 0xA5C}, // Gurmukhi
    {0xA66, 0xA74}, // Gurmukhi
    {0xA81, 0xA83}, // Gujarati
    {0xA85, 0xA8D}, // Gujarati
    {0xA8F, 0xA91}, // Gujarati
    {0xA93, 0xAA8}, // Gujarati
    {0xAAA, 0xAB0}, // Gujarati
    {0xAB2, 0xAB3}, // Gujarati
    {0xAB5, 0xAB9}, // Gujarati
    {0xABC, 0xAC5}, // Gujarati
    {0xAC7, 0xAC9}, // Gujarati
    {0xACB, 0xACD}, // Gujarati
    {0xAD0, 0xAD0}, // Gujarati
    {0xAE0, 0xAE3}, // Gujarati
    {0xAE6, 0xAEF}, // Gujarati
    {0xAFA, 0xAFF}, // Gujarati
    {0xB01, 0xB03}, // Oriya
    {0xB05, 0xB0C}, // Oriya
    {0xB0F, 0xB10}, // Oriya
    {0xB13, 0xB28}, // Oriya
    {0xB2A, 0xB30}, // Oriya
    {0xB32, 0xB33}, // Oriya
    {0xB35, 0xB39}, // Oriya
    {0xB3C, 0xB43}, // Oriya
    {0xB47, 0xB48}, // Oriya
    {0xB4B, 0xB4D}, // Oriya
    {0xB55, 0xB57}, // Oriya
    {0xB5F, 0xB61}, // Oriya
    {0xB66, 0xB6F}, // Oriya
    {0xB71, 0xB71}, // Oriya
    {0xB82, 0xB83}, // Tamil
    {0xB85, 0xB8A}, // Tamil
    {0xB8E, 0xB90}, // Tamil
    {0xB92, 0xB95}, // Tamil
    {0xB99, 0xB9A}, // Tamil
    {0xB9C, 0xB9C}, // Tamil
    {0xB9E, 0xB9F}, // Tamil
    {0xBA3, 0xBA4}, // Tamil
    {0xBA8, 0xBAA}, // Tamil
    {0xBAE, 0xBB9}, // Tamil
    {0xBBE, 0xBC2}, // Tamil
    {0xBC6, 0xBC8}, // Tamil
    {0xBCA, 0xBCD}, // Tamil
    {0xBD0, 0xBD0}, // Tamil
    {0xBD7, 0xBD7}, // Tamil
    {0xBE6, 0xBEF}, // Tamil
    {0xC01, 0xC0C}, // Telugu
    {0xC0E, 0xC10}, // Telugu
    {0xC12, 0xC28}, // Telugu
    {0xC2A, 0xC33}, // Telugu
    {0xC35, 0xC39}, // Telugu
    {0xC3C, 0xC44}, // Telugu
    {0xC46, 0xC48}, // Telugu
    {0xC4A, 0xC4D}, // Telugu
    {0xC55, 0xC56}, // Telugu
    {0xC5D, 0xC5D}, // Telugu
    {0xC60, 0xC61}, // Telugu
    {0xC66, 0xC6F}, // Telugu
    {0xC80, 0xC80}, // Kannada
    {0xC82, 0xC83}, // Kannada
    {0xC85, 0xC8C}, // Kannada
    {0xC8E, 0xC90}, // Kannada
    {0xC92, 0xCA8}, // Kannada
    {0xCAA, 0xCB3}, // Kannada
    {0xCB5, 0xCB9}, // Kannada
    {0xCBC, 0xCC4}, // Kannada
    {0xCC6, 0xCC8}, // Kannada
    {0xCCA, 0xCCD}, // Kannada
    {0xCD5, 0xCD6}, // Kannada
    {0xCDD, 0xCDD}, // Kannada
    {0xCE0, 0xCE3}, // Kannada
    {0xCE6, 0xCEF}, // Kannada
    {0xCF1, 0xCF2}, // Kannada
    {0xD00, 0xD00}, // Malayalam
    {0xD02, 0xD03}, // Malayalam
    {0xD05, 0xD0C}, // Malayalam
    {0xD0E, 0xD10}, // Malayalam
    {0xD12, 0xD3A}, // Malayalam
    {0xD3D, 0xD43}, // Malayalam
    {0xD46, 0xD48}, // Malayalam
    {0xD4A, 0xD4E}, // Malayalam
    {0xD54, 0xD57}, // Malayalam
    {0xD60, 0xD61}, // Malayalam
    {0xD66, 0xD6F}, // Malayalam
    {0xD7A, 0xD7F}, // Malayalam
    {0xD82, 0xD83}, // Sinhala
    {0xD85, 0xD8E}, // Sinhala
    {0xD91, 0xD96}, // Sinhala
    {0xD9A, 0xDA5}, // Sinhala
    {0xDA7, 0xDB1}, // Sinhala
    {0xDB3, 0xDBB}, // Sinhala
    {0xDBD, 0xDBD}, // Sinhala
    {0xDC0, 0xDC6}, // Sinhala
    {0xDCA, 0xDCA}, // Sinhala
    {0xDCF, 0xDD4}, // Sinhala
    {0xDD6, 0xDD6}, // Sinhala
    {0xDD8, 0xDDE}, // Sinhala
    {0xDF2, 0xDF2}, // Sinhala
    {0xE01, 0xE32}, // Thai
    {0xE34, 0xE3A}, // Thai
    {0xE40, 0xE4E}, // Thai
    {0xE50, 0xE59}, // Thai
    {0xE81, 0xE82}, // Lao
    {0xE84, 0xE84}, // Lao
    {0xE86, 0xE8A}, // Lao
    {0xE8C, 0xEA3}, // Lao
    {0xEA5, 0xEA5}, // Lao
    {0xEA7, 0xEB2}, // Lao
    {0xEB4, 0xEBD}, // Lao
    {0xEC0, 0xEC4}, // Lao
    {0xEC6, 0xEC6}, // Lao
    {0xEC8, 0xECD}, // Lao
    {0xED0, 0xED9}, // Lao
    {0xEDE, 0xEDF}, // Lao
    {0xF00, 0xF00}, // Tibetan
    {0xF0B, 0xF0B}, // Tibetan
    {0xF20, 0xF29}, // Tibetan
    {0xF35, 0xF35}, // Tibetan
    {0xF37, 0xF37}, // Tibetan
    {0xF3E, 0xF42}, // Tibetan
    {0xF44, 0xF47}, // Tibetan
    {0xF49, 0xF4C}, // Tibetan
    {0xF4E, 0xF51}, // Tibetan
    {0xF53, 0xF56}, // Tibetan
    {0xF58, 0xF5B}, // Tibetan
    {0xF5D, 0xF68}, // Tibetan
    {0xF6A, 0xF6C}, // Tibetan
    {0xF71, 0xF72}, // Tibetan
    {0xF74, 0xF74}, // Tibetan
    {0xF7A, 0xF80}, // Tibetan
    {0xF82, 0xF84}, // Tibetan
    {0xF86, 0xF92}, // Tibetan
    {0xF94, 0xF97}, // Tibetan
    {0xF99, 0xF9C}, // Tibetan
    {0xF9E, 0xFA1}, // Tibetan
    {0xFA3, 0xFA6}, // Tibetan
    {0xFA8, 0xFAB}, // Tibetan
    {0xFAD, 0xFB8}, // Tibetan
    {0xFBA, 0xFBC}, // Tibetan
    {0xFC6, 0xFC6}, // Tibetan
    {0x1000, 0x1049}, // Myanmar
    {0x1050, 0x109D}, // Myanmar
    {0x10C7, 0x10C7}, // Georgian
    {0x10CD, 0x10CD}, // Georgian
    {0x10D0, 0x10F0}, // Georgian
    {0x10F7, 0x10FA}, // Georgian
    {0x10FD, 0x10FF}, // Georgian
    {0x1200, 0x1248}, // Ethiopic
    {0x124A, 0x124D}, // Ethiopic
    {0x1250, 0x1256}, // Ethiopic
    {0x1258, 0x1258}, // Ethiopic
    {0x125A, 0x125D}, // Ethiopic
    {0x1260, 0x1288}, // Ethiopic
    {0x128A, 0x128D}, // Ethiopic
    {0x1290, 0x12B0}, // Ethiopic
    {0x12B2, 0x12B5}, // Ethiopic
    {0x12B8, 0x12BE}, // Ethiopic
    {0x12C0, 0x12C0}, // Ethiopic
    {0x12C2, 0x12C5}, // Ethiopic
    {0x12C8, 0x12D6}, // Ethiopic
    {0x12D8, 0x1310}, // Ethiopic
    {0x1312, 0x1315}, // Ethiopic
    {0x1318, 0x135A}, // Ethiopic
    {0x135D, 0x135F}, // Ethiopic
    {0x1380, 0x138F}, // Ethiopic
    // skipped 0x13A0 Cherokee (Limited)
    // skipped 0x1400 Canadian_Aboriginal (Limited)
    // skipped 0x1681 Ogham (Excluded)
    // skipped 0x16A0 Runic (Excluded)
    // skipped 0x16EE Runic (Excluded)
    // skipped 0x1700 Tagalog (Excluded)
    // skipped 0x1720 Hanunoo (Excluded)
    // skipped 0x1740 Buhid (Excluded)
    // skipped 0x1760 Tagbanwa (Excluded)
    {0x1780, 0x17A2}, // Khmer
    {0x17A5, 0x17A7}, // Khmer
    {0x17A9, 0x17B3}, // Khmer
    {0x17B6, 0x17CD}, // Khmer
    {0x17D0, 0x17D0}, // Khmer
    {0x17D2, 0x17D2}, // Khmer
    {0x17D7, 0x17D7}, // Khmer
    {0x17DC, 0x17DC}, // Khmer
    {0x17E0, 0x17E9}, // Khmer
    // skipped 0x1800 Mongolian (Excluded)
    // skipped 0x18B0 Canadian_Aboriginal (Limited)
    // skipped 0x1900 Limbu (Limited)
    // skipped 0x1950 Tai_Le (Limited)
    // skipped 0x1980 New_Tai_Lue (Limited)
    // skipped 0x1A00 Buginese (Excluded)
    // skipped 0x1A20 Tai_Tham (Limited)
    // skipped 0x1B00 Balinese (Limited)
    // skipped 0x1B80 Sundanese (Limited)
    // skipped 0x1BC0 Batak (Limited)
    // skipped 0x1C00 Lepcha (Limited)
    // skipped 0x1C50 Ol_Chiki (Limited)
    {0x1C90, 0x1CBA}, // Georgian
    {0x1CBD, 0x1CBF}, // Georgian
    // skipped 0x1CC0 Sundanese (Limited)
    {0x1E00, 0x1E99}, // Latin
    {0x1E9E, 0x1E9E}, // Latin
    {0x1EA0, 0x1EF9}, // Latin
    {0x1F00, 0x1F15}, // Greek
    {0x1F18, 0x1F1D}, // Greek
    {0x1F20, 0x1F45}, // Greek
    {0x1F48, 0x1F4D}, // Greek
    {0x1F50, 0x1F57}, // Greek
    {0x1F59, 0x1F59}, // Greek
    {0x1F5B, 0x1F5B}, // Greek
    {0x1F5D, 0x1F5D}, // Greek
    {0x1F5F, 0x1F70}, // Greek
    {0x1F72, 0x1F72}, // Greek
    {0x1F74, 0x1F74}, // Greek
    {0x1F76, 0x1F76}, // Greek
    {0x1F78, 0x1F78}, // Greek
    {0x1F7A, 0x1F7A}, // Greek
    {0x1F7C, 0x1F7C}, // Greek
    {0x1F80, 0x1FB4}, // Greek
    {0x1FB6, 0x1FBA}, // Greek
    {0x1FBC, 0x1FBC}, // Greek
    {0x1FC2, 0x1FC4}, // Greek
    {0x1FC6, 0x1FC8}, // Greek
    {0x1FCA, 0x1FCA}, // Greek
    {0x1FCC, 0x1FCC}, // Greek
    {0x1FD0, 0x1FD2}, // Greek
    {0x1FD6, 0x1FDA}, // Greek
    {0x1FE0, 0x1FE2}, // Greek
    {0x1FE4, 0x1FEA}, // Greek
    {0x1FEC, 0x1FEC}, // Greek
    {0x1FF2, 0x1FF4}, // Greek
    {0x1FF6, 0x1FF8}, // Greek
    {0x1FFA, 0x1FFA}, // Greek
    {0x1FFC, 0x1FFC}, // Greek
    {0x200C, 0x200D}, // Inherited
    // skipped 0x2C00 Glagolitic (Excluded)
    // skipped 0x2C80 Coptic (Excluded)
    {0x2D27, 0x2D27}, // Georgian
    {0x2D2D, 0x2D2D}, // Georgian
    // skipped 0x2D30 Tifinagh (Limited)
    {0x2D80, 0x2D96}, // Ethiopic
    {0x2DA0, 0x2DA6}, // Ethiopic
    {0x2DA8, 0x2DAE}, // Ethiopic
    {0x2DB0, 0x2DB6}, // Ethiopic
    {0x2DB8, 0x2DBE}, // Ethiopic
    {0x2DC0, 0x2DC6}, // Ethiopic
    {0x2DC8, 0x2DCE}, // Ethiopic
    {0x2DD0, 0x2DD6}, // Ethiopic
    {0x2DD8, 0x2DDE}, // Ethiopic
    {0x3005, 0x3007}, // Han
    {0x3041, 0x3096}, // Hiragana
    {0x3099, 0x309A}, // Inherited
    {0x309D, 0x309E}, // Hiragana
    {0x30A0, 0x30FE}, // Common
    {0x3105, 0x312D}, // Bopomofo
    {0x312F, 0x312F}, // Bopomofo
    {0x31A0, 0x31BF}, // Bopomofo
    {0x3400, 0x4DBF}, // Han
    {0x4E00, 0x9FFF}, // Han
    // skipped 0xA000 Yi (Limited)
    // skipped 0xA4D0 Lisu (Limited)
    // skipped 0xA500 Vai (Limited)
    {0xA67F, 0xA67F}, // Cyrillic
    // skipped 0xA6A0 Bamum (Limited)
    {0xA717, 0xA71F}, // Common
    {0xA788, 0xA788}, // Common
    {0xA78D, 0xA78D}, // Latin
    {0xA792, 0xA793}, // Latin
    {0xA7AA, 0xA7AA}, // Latin
    {0xA7AE, 0xA7AE}, // Latin
    {0xA7B8, 0xA7B9}, // Latin
    {0xA7C0, 0xA7CA}, // Latin
    {0xA7D0, 0xA7D1}, // Latin
    {0xA7D3, 0xA7D3}, // Latin
    {0xA7D5, 0xA7D9}, // Latin
    // skipped 0xA800 Syloti_Nagri (Limited)
    // skipped 0xA840 Phags_Pa (Excluded)
    // skipped 0xA880 Saurashtra (Limited)
    // skipped 0xA900 Kayah_Li (Limited)
    // skipped 0xA92F Kayah_Li (Limited)
    // skipped 0xA930 Rejang (Excluded)
    {0xA9E7, 0xA9FE}, // Myanmar
    // skipped 0xA980 Javanese (Limited)
    // skipped 0xA9D0 Javanese (Limited)
    // skipped 0xAA00 Cham (Limited)
    {0xAA60, 0xAA76}, // Myanmar
    {0xAA7A, 0xAA7F}, // Myanmar
    // skipped 0xAA80 Tai_Viet (Limited)
    // skipped 0xAAE0 Meetei_Mayek (Limited)
    {0xAB01, 0xAB06}, // Ethiopic
    {0xAB09, 0xAB0E}, // Ethiopic
    {0xAB11, 0xAB16}, // Ethiopic
    {0xAB20, 0xAB26}, // Ethiopic
    {0xAB28, 0xAB2E}, // Ethiopic
    {0xAB66, 0xAB67}, // Latin
    // skipped 0xAB70 Cherokee (Limited)
    // skipped 0xABC0 Meetei_Mayek (Limited)
    {0xAC00, 0xD7A3}, // Hangul
    {0xFA0E, 0xFA0F}, // Han
    {0xFA11, 0xFA11}, // Han
    {0xFA13, 0xFA14}, // Han
    {0xFA1F, 0xFA1F}, // Han
    {0xFA21, 0xFA21}, // Han
    {0xFA23, 0xFA24}, // Han
    {0xFA27, 0xFA29}, // Han
    // FE31-FE44 Pd,Ps,Pe
    // FE47-FE6B, Common (Ps,Pe) + SMALL EQUALS SIGN. not XID

    // skipped 0x10000 Linear_B (Excluded)
    // skipped 0x10280 Lycian (Excluded)
    // skipped 0x102A0 Carian (Excluded)
    // skipped 0x10300 Old_Italic (Excluded)
    // skipped 0x10330 Gothic (Excluded)
    // skipped 0x10350 Old_Permic (Excluded)
    // skipped 0x10380 Ugaritic (Excluded)
    // skipped 0x103A0 Old_Persian (Excluded)
    // skipped 0x10400 Deseret (Excluded)
    // skipped 0x10450 Shavian (Excluded)
    // skipped 0x10480 Osmanya (Excluded)
    // skipped 0x104B0 Osage (Limited)
    // skipped 0x10500 Elbasan (Excluded)
    // skipped 0x10530 Caucasian_Albanian (Excluded)
    // skipped 0x10570 Vithkuqi (Excluded)
    // skipped 0x10600 Linear_A (Excluded)
    // skipped 0x10800 Cypriot (Excluded)
    // skipped 0x10840 Imperial_Aramaic (Excluded)
    // skipped 0x10860 Palmyrene (Excluded)
    // skipped 0x10880 Nabataean (Excluded)
    // skipped 0x108E0 Hatran (Excluded)
    // skipped 0x10900 Phoenician (Excluded)
    // skipped 0x10920 Lydian (Excluded)
    // skipped 0x10980 Meroitic_Hieroglyphs (Excluded)
    // skipped 0x109A0 Meroitic_Cursive (Excluded)
    // skipped 0x10A00 Kharoshthi (Excluded)
    // skipped 0x10A60 Old_South_Arabian (Excluded)
    // skipped 0x10A80 Old_North_Arabian (Excluded)
    // skipped 0x10AC0 Manichaean (Excluded)
    // skipped 0x10B00 Avestan (Excluded)
    // skipped 0x10B40 Inscriptional_Parthian (Excluded)
    // skipped 0x10B60 Inscriptional_Pahlavi (Excluded)
    // skipped 0x10B80 Psalter_Pahlavi (Excluded)
    // skipped 0x10C00 Old_Turkic (Excluded)
    // skipped 0x10C80 Old_Hungarian (Excluded)
    // skipped 0x10D00 Hanifi_Rohingya (Limited)
    // skipped 0x10E80 Yezidi (Excluded)
    // skipped 0x10F00 Old_Sogdian (Excluded)
    // skipped 0x10F30 Sogdian (Excluded)
    // skipped 0x10F70 Old_Uyghur (Excluded)
    // skipped 0x10FB0 Chorasmian (Excluded)
    // skipped 0x10FE0 Elymaic (Excluded)
    // skipped 0x11000 Brahmi (Excluded)
    // skipped 0x11080 Kaithi (Excluded)
    // skipped 0x110D0 Sora_Sompeng (Excluded)
    // skipped 0x11100 Chakma (Limited)
    // skipped 0x11150 Mahajani (Excluded)
    // skipped 0x11180 Sharada (Excluded)
    // skipped 0x11200 Khojki (Excluded)
    // skipped 0x11280 Multani (Excluded)
    // skipped 0x112B0 Khudawadi (Excluded)
    // skipped 0x11300 Grantha (Excluded)
    {0x1133B, 0x1133B}, // Inherited
    // skipped 0x1133C Grantha (Excluded)
    // skipped 0x11400 Newa (Limited)
    // skipped 0x11480 Tirhuta (Excluded)
    // skipped 0x11580 Siddham (Excluded)
    // skipped 0x11600 Modi (Excluded)
    // skipped 0x11660 Mongolian (Excluded)
    // skipped 0x11680 Takri (Excluded)
    // skipped 0x11700 Ahom (Excluded)
    // skipped 0x11800 Dogra (Excluded)
    // skipped 0x118A0 Warang_Citi (Excluded)
    // skipped 0x11900 Dives_Akuru (Excluded)
    // skipped 0x119A0 Nandinagari (Excluded)
    // skipped 0x11A00 Zanabazar_Square (Excluded)
    // skipped 0x11A50 Soyombo (Excluded)
    // skipped 0x11AB0 Canadian_Aboriginal (Limited)
    // skipped 0x11AC0 Pau_Cin_Hau (Excluded)
    // skipped 0x11C00 Bhaiksuki (Excluded)
    // skipped 0x11C70 Marchen (Excluded)
    // skipped 0x11D00 Masaram_Gondi (Excluded)
    // skipped 0x11D60 Gunjala_Gondi (Excluded)
    // skipped 0x11EE0 Makasar (Excluded)
    // skipped 0x11FB0 Lisu (Limited)
    // skipped 0x12000 Cuneiform (Excluded)
    // skipped 0x12F90 Cypro_Minoan (Excluded)
    // skipped 0x13000 Egyptian_Hieroglyphs (Excluded)
    // skipped 0x14400 Anatolian_Hieroglyphs (Excluded)
    // skipped 0x16800 Bamum (Limited)
    // skipped 0x16A40 Mro (Excluded)
    // skipped 0x16A70 Tangsa (Excluded)
    // skipped 0x16AD0 Bassa_Vah (Excluded)
    // skipped 0x16B00 Pahawh_Hmong (Excluded)
    // skipped 0x16E40 Medefaidrin (Excluded)
    // skipped 0x16F00 Miao (Limited)
    // skipped 0x16FE0 Tangut (Excluded)
    // skipped 0x16FE1 Nushu (Excluded)
    {0x16FF0, 0x16FF1}, // Han
    // skipped 0x16FE4 Khitan_Small_Script (Excluded)
    // skipped 0x17000 Tangut (Excluded)
    // skipped 0x18B00 Khitan_Small_Script (Excluded)
    // skipped 0x18D00 Tangut (Excluded)
    {0x1B11F, 0x1B122}, // Hiragana
    {0x1B150, 0x1B152}, // Hiragana
    {0x1B164, 0x1B167}, // Katakana
    // skipped 0x1B170 Nushu (Excluded)
    // skipped 0x1BC00 Duployan (Excluded)
    // skipped 0x1D800 SignWriting (Excluded)
    {0x1DF00, 0x1DF1E}, // Latin
    // skipped 0x1E000 Glagolitic (Excluded)
    // skipped 0x1E100 Nyiakeng_Puachue_Hmong (Limited)
    // skipped 0x1E290 Toto (Excluded)
    // skipped 0x1E2C0 Wancho (Limited)
    {0x1E7E0, 0x1E7E6}, // Ethiopic
    {0x1E7E8, 0x1E7EB}, // Ethiopic
    {0x1E7ED, 0x1E7EE}, // Ethiopic
    {0x1E7F0, 0x1E7FE}, // Ethiopic
    // skipped 0x1E800 Mende_Kikakui (Excluded)
    // skipped 0x1E900 Adlam (Limited)
    {0x20000, 0x2A6DF}, // Han
    {0x2A700, 0x2B738}, // Han
    {0x2B740, 0x2B81D}, // Han
    {0x2B820, 0x2CEA1}, // Han
    {0x2CEB0, 0x2EBE0}, // Han
    {0x30000, 0x3134A}, // Han

    /* ?? manual leftovers
    {0x111E1, 0x111F4}, // Sinhala
    {0x1133B, 0x1133B}, // Inherited
    {0x11FC0, 0x11FFF}, // Tamil
    {0x16FE2, 0x16FE3}, // Han
    {0x16FF0, 0x16FF1}, // Han
    {0x1AFF0, 0x1B122}, // Katakana
    {0x1B150, 0x1B152}, // Hiragana
    {0x1B164, 0x1B167}, // Katakana
    {0x1BCA0, 0x1BCA3}, // Common
    {0x1CF00, 0x1CF46}, // Inherited
    {0x1CF50, 0x1D1EA}, // Common
    {0x1D200, 0x1D245}, // Greek
    {0x1D2E0, 0x1D7FF}, // Common
    {0x1DF00, 0x1DF1E}, // Latin
    {0x1E7E0, 0x1E7FE}, // Ethiopic
    {0x1EC71, 0x1ED3D}, // Common
    {0x1EE00, 0x1EEF1}, // Arabic
    {0x1F000, 0x1FBF9}, // Common
    {0x20000, 0x20000}, // Han
    {0x30000, 0x3134A}, // Han
    {0xE0001, 0xE007F}, // Common Restr?
    {0xE0100, 0xE01EF}, // Inherited Restr?
    */
};
#endif

#endif
